// All 50 Dishes — Spice Route Indian Restaurant
window.DISHES = {
  starters:[
  {id:"samosa",name:"Samosa Chaat",price:180,badge:"VEG",region:"Punjab",img:"images/samosa.jpg",emoji:"&#129455;",desc:"Crispy samosas topped with chole, sweet chutneys, yoghurt and sev. A street-food classic elevated.",ingredients:["Wheat flour","Potato","Peas","Chana","Tamarind chutney","Green chutney","Yoghurt","Sev","Chaat masala","Red chilli"],cal:310,protein:"8g",carbs:"42g",fat:"11g",spice:"Medium",isNew:false},
  {id:"ptikka",name:"Paneer Tikka",price:320,badge:"VEG",region:"Punjab",img:"images/paneer-tikka.jpg",emoji:"&#129472;",desc:"Marinated cottage cheese cubes grilled in tandoor with bell peppers, onions and mint chutney.",ingredients:["Paneer","Bell peppers","Onion","Hung curd","Ginger-garlic paste","Ajwain","Red chilli","Garam masala","Kasuri methi","Lemon"],cal:380,protein:"18g",carbs:"14g",fat:"28g",spice:"Mild",isNew:false},
  {id:"ctikka",name:"Chicken Malai Tikka",price:380,badge:"NON-VEG",region:"Mughlai",img:"images/chicken-tikka.jpg",emoji:"&#127831;",desc:"Tender chicken marinated in cream, cashew paste and mild spices. Melt-in-mouth texture.",ingredients:["Chicken breast","Fresh cream","Cashew paste","Curd","Green chilli","Ginger","Garlic","Cardamom","White pepper","Lemon"],cal:420,protein:"34g",carbs:"6g",fat:"29g",spice:"Mild",isNew:false},
  {id:"dahipuri",name:"Dahi Puri",price:150,badge:"VEG",region:"Mumbai",img:"images/dahi-puri.jpg",emoji:"&#129381;",desc:"Hollow puris filled with spiced potato, sweet yoghurt, tamarind and green chutney. Mumbai favourite.",ingredients:["Semolina puri","Boiled potato","Yoghurt","Tamarind chutney","Green chutney","Onion","Sev","Pomegranate","Chaat masala","Black salt"],cal:220,protein:"6g",carbs:"34g",fat:"7g",spice:"Mild",isNew:false},
  {id:"seekh",name:"Veg Seekh Kebab",price:280,badge:"VEG",region:"Awadh",img:"images/seekh-kebab.jpg",emoji:"&#127830;",desc:"Minced vegetables and paneer shaped on skewers, grilled in tandoor with chaat masala finish.",ingredients:["Paneer","Mixed vegetables","Besan","Ginger","Green chilli","Onion","Coriander","Garam masala","Chaat masala","Mustard oil"],cal:290,protein:"12g",carbs:"22g",fat:"17g",spice:"Medium",isNew:false},
  {id:"papdi",name:"Papdi Chaat",price:160,badge:"VEG",region:"Delhi",img:"images/papdi-chaat.jpg",emoji:"&#129479;",desc:"Crispy flour crisps layered with boiled potato, chickpeas, chutneys and fresh yoghurt. Delhi street classic.",ingredients:["Papdi","Boiled potato","Chickpeas","Yoghurt","Tamarind chutney","Green chutney","Sev","Pomegranate","Chaat masala","Coriander"],cal:280,protein:"7g",carbs:"38g",fat:"9g",spice:"Medium",isNew:true},
  {id:"alootikki",name:"Aloo Tikki",price:140,badge:"VEG",region:"Punjab",img:"images/aloo-tikki.jpg",emoji:"&#127839;",desc:"Golden potato cutlets spiced with cumin and coriander, pan-fried crispy. Served with chutneys.",ingredients:["Boiled potato","Cumin seeds","Green chilli","Coriander","Ginger","Breadcrumbs","Red chilli","Amchur","Oil"],cal:250,protein:"5g",carbs:"36g",fat:"8g",spice:"Medium",isNew:true},
  {id:"harabharakabab",name:"Hara Bhara Kabab",price:260,badge:"VEG",region:"Delhi",img:"images/hara-bhara-kabab.jpg",emoji:"&#129382;",desc:"Vibrant green spinach, peas and paneer patties infused with herbs. Served with mint chutney.",ingredients:["Spinach","Green peas","Paneer","Potato","Ginger","Green chilli","Coriander","Garam masala","Cornflour","Lemon"],cal:230,protein:"10g",carbs:"24g",fat:"10g",spice:"Mild",isNew:true},
  {id:"fishamritsari",name:"Fish Amritsari",price:360,badge:"NON-VEG",region:"Punjab",img:"images/fish-amritsari.jpg",emoji:"&#128031;",desc:"Crispy battered fish marinated in Amritsari spices and deep fried golden. A Punjabi specialty.",ingredients:["Fish fillet","Besan","Ajwain","Ginger-garlic","Red chilli","Turmeric","Lemon","Carom seeds","Oil","Coriander"],cal:390,protein:"28g",carbs:"18g",fat:"22g",spice:"Hot",isNew:true},
  {id:"muttongalouti",name:"Mutton Galouti Kebab",price:440,badge:"NON-VEG",region:"Awadh",img:"images/mutton-galouti.jpg",emoji:"&#129385;",desc:"Melt-in-mouth minced mutton kebab with 100 spices, grilled on tawa. Lucknowi royal heritage.",ingredients:["Minced mutton","Raw papaya","Fried onion","Saffron","Cardamom","Cloves","Cinnamon","Garam masala","Ghee","Rose water"],cal:420,protein:"32g",carbs:"8g",fat:"30g",spice:"Medium",isNew:true}
],
  breads:[
  {id:"shorba",name:"Tamatar Shorba",price:160,badge:"VEG",region:"Mughlai",img:"images/tomato-shorba.jpg",emoji:"&#127858;",desc:"Royal Mughlai tomato soup with fresh cream, cardamom, ginger and coriander. Silky smooth.",ingredients:["Tomatoes","Fresh cream","Onion","Ginger","Garlic","Cardamom","Bay leaf","Cumin","Coriander","Butter"],cal:160,protein:"4g",carbs:"18g",fat:"9g",spice:"Mild",isNew:false},
  {id:"daltadka",name:"Dal Tadka",price:220,badge:"VEG",region:"Punjab",img:"images/dal-tadka.jpg",emoji:"&#129365;",desc:"Yellow lentils tempered with cumin, garlic, dried red chillies and ghee. Soul-warming comfort.",ingredients:["Yellow lentils","Ghee","Cumin seeds","Garlic","Onion","Tomato","Dried red chilli","Garam masala","Coriander","Turmeric"],cal:240,protein:"12g",carbs:"30g",fat:"8g",spice:"Mild",isNew:false},
  {id:"naan",name:"Garlic Butter Naan",price:80,badge:"VEG",region:"Punjab",img:"images/garlic-naan.jpg",emoji:"&#129362;",desc:"Soft leavened bread baked in tandoor, brushed with garlic butter and coriander.",ingredients:["Maida","Yeast","Milk","Curd","Garlic","Butter","Coriander","Salt","Sugar","Oil"],cal:260,protein:"7g",carbs:"40g",fat:"9g",spice:"None",isNew:false},
  {id:"roti",name:"Tandoori Roti",price:40,badge:"VEG",region:"North India",img:"images/tandoori-roti.jpg",emoji:"&#129362;",desc:"Whole wheat flatbread cooked directly on tandoor walls. Light, wholesome, traditional.",ingredients:["Whole wheat flour","Water","Salt","Ghee"],cal:120,protein:"4g",carbs:"22g",fat:"3g",spice:"None",isNew:false},
  {id:"basket",name:"Royal Bread Basket",price:180,badge:"VEG",region:"North India",img:"images/bread-basket.jpg",emoji:"&#127838;",desc:"Assorted naan, paratha, kulcha and missi roti. Served with three dipping chutneys.",ingredients:["Naan","Paratha","Kulcha","Missi roti","Mint chutney","Tamarind chutney","Pickle"],cal:480,protein:"14g",carbs:"70g",fat:"16g",spice:"None",isNew:false},
  {id:"mulligatawny",name:"Mulligatawny Soup",price:180,badge:"VEG",region:"Tamil Nadu",img:"images/mulligatawny.jpg",emoji:"&#127858;",desc:"Anglo-Indian lentil soup with coconut milk, curry leaves, tamarind and South Indian spices.",ingredients:["Lentils","Coconut milk","Tamarind","Curry leaves","Cumin","Pepper","Turmeric","Ginger","Tomato","Onion"],cal:200,protein:"8g",carbs:"24g",fat:"8g",spice:"Medium",isNew:true},
  {id:"peshwarinaan",name:"Peshwari Naan",price:100,badge:"VEG",region:"Punjab",img:"images/peshwari-naan.jpg",emoji:"&#129362;",desc:"Soft naan stuffed with coconut, almonds and sultanas. Sweet, fragrant, indulgent.",ingredients:["Maida","Coconut","Almonds","Sultanas","Ghee","Yeast","Sugar","Salt"],cal:310,protein:"8g",carbs:"48g",fat:"11g",spice:"None",isNew:true},
  {id:"lacchaparatha",name:"Lachha Paratha",price:60,badge:"VEG",region:"Punjab",img:"images/lachha-paratha.jpg",emoji:"&#129362;",desc:"Flaky layered whole wheat flatbread, coated in ghee. Crispy outside, soft inside.",ingredients:["Whole wheat flour","Ghee","Salt","Water"],cal:180,protein:"5g",carbs:"28g",fat:"7g",spice:"None",isNew:true},
  {id:"stuffedkulcha",name:"Stuffed Kulcha",price:120,badge:"VEG",region:"Punjab",img:"images/stuffed-kulcha.jpg",emoji:"&#129362;",desc:"Leavened bread stuffed with spiced potato and paneer, baked in tandoor. Classic Amritsari.",ingredients:["Maida","Boiled potato","Paneer","Onion","Green chilli","Coriander","Cumin","Butter","Yeast"],cal:290,protein:"9g",carbs:"42g",fat:"10g",spice:"Mild",isNew:true},
  {id:"missiroti",name:"Missi Roti",price:50,badge:"VEG",region:"Rajasthan",img:"images/missi-roti.jpg",emoji:"&#129362;",desc:"Whole wheat and chickpea flour flatbread with fenugreek and spices. Rustic and nutritious.",ingredients:["Whole wheat flour","Besan","Fenugreek","Ajwain","Green chilli","Ginger","Ghee","Salt"],cal:140,protein:"6g",carbs:"20g",fat:"5g",spice:"Mild",isNew:true}
],
  veg:[
  {id:"pbm",name:"Paneer Butter Masala",price:320,badge:"VEG",region:"Punjab",img:"images/paneer-butter-masala.jpg",emoji:"&#127859;",desc:"Rich tomato-cream gravy with soft paneer cubes, kasuri methi and butter.",ingredients:["Paneer","Tomato","Butter","Fresh cream","Cashews","Onion","Ginger","Garlic","Kasuri methi","Garam masala"],cal:420,protein:"16g",carbs:"18g",fat:"32g",spice:"Mild",isNew:false},
  {id:"palak",name:"Palak Paneer",price:300,badge:"VEG",region:"Punjab",img:"images/palak-paneer.jpg",emoji:"&#129382;",desc:"Blanched spinach puree with cottage cheese, garam masala and ginger. Nutritious and aromatic.",ingredients:["Spinach","Paneer","Onion","Tomato","Ginger","Garlic","Green chilli","Garam masala","Cream","Cumin"],cal:360,protein:"15g",carbs:"14g",fat:"26g",spice:"Mild",isNew:false},
  {id:"dalm",name:"Dal Makhani",price:280,badge:"VEG",region:"Punjab",img:"images/dal-makhani.jpg",emoji:"&#129365;",desc:"Slow-cooked black lentils with butter, cream and tomatoes simmered overnight.",ingredients:["Black lentils","Kidney beans","Butter","Cream","Tomato","Onion","Ginger","Garlic","Garam masala","Cumin"],cal:390,protein:"14g",carbs:"34g",fat:"20g",spice:"Mild",isNew:false},
  {id:"chana",name:"Chana Masala",price:260,badge:"VEG",region:"Punjab",img:"images/chana-masala.jpg",emoji:"&#129384;",desc:"Hearty chickpeas in tangy spiced tomato gravy with amchur, cumin and coriander.",ingredients:["Chickpeas","Tomato","Onion","Ginger","Garlic","Amchur","Cumin","Coriander","Garam masala","Pomegranate seeds"],cal:340,protein:"14g",carbs:"46g",fat:"10g",spice:"Medium",isNew:false},
  {id:"vbiriyani",name:"Veg Dum Biryani",price:340,badge:"VEG",region:"Hyderabad",img:"images/veg-biryani.jpg",emoji:"&#127859;",desc:"Fragrant basmati layered with seasonal vegetables, saffron and rose water. Sealed dum-style.",ingredients:["Basmati rice","Mixed vegetables","Saffron","Rose water","Fried onions","Ghee","Whole spices","Mint","Curd","Kewra"],cal:520,protein:"10g",carbs:"80g",fat:"18g",spice:"Medium",isNew:false},
  {id:"navratankorma",name:"Navratan Korma",price:320,badge:"VEG",region:"Mughlai",img:"images/navratan-korma.jpg",emoji:"&#127859;",desc:"Nine-jewel curry with mixed vegetables, fruits, paneer and nuts in rich cashew gravy.",ingredients:["Mixed vegetables","Paneer","Cashews","Cream","Tomato","Onion","Cardamom","Saffron","Raisins","Pistachios"],cal:380,protein:"12g",carbs:"28g",fat:"24g",spice:"Mild",isNew:true},
  {id:"baingan",name:"Baingan Bharta",price:260,badge:"VEG",region:"Punjab",img:"images/baingan-bharta.jpg",emoji:"&#129382;",desc:"Smoky fire-roasted aubergine mashed with tomatoes, onions, ginger and mustard oil.",ingredients:["Aubergine","Tomato","Onion","Ginger","Garlic","Green chilli","Mustard oil","Cumin","Coriander","Turmeric"],cal:210,protein:"5g",carbs:"18g",fat:"12g",spice:"Medium",isNew:true},
  {id:"kadaipaneer",name:"Kadai Paneer",price:310,badge:"VEG",region:"Punjab",img:"images/kadai-paneer.jpg",emoji:"&#127859;",desc:"Paneer and peppers cooked in freshly ground coriander-chilli masala in an iron kadai.",ingredients:["Paneer","Bell peppers","Onion","Tomato","Coriander seeds","Cumin","Dried chilli","Ginger","Garlic","Kasuri methi"],cal:350,protein:"14g",carbs:"16g",fat:"22g",spice:"Medium",isNew:true},
  {id:"rajma",name:"Rajma Masala",price:240,badge:"VEG",region:"Punjab",img:"images/rajma-masala.jpg",emoji:"&#129384;",desc:"Slow-cooked kidney beans in thick spiced onion-tomato gravy. Punjab comfort food.",ingredients:["Kidney beans","Tomato","Onion","Ginger","Garlic","Cumin","Coriander","Garam masala","Turmeric","Butter"],cal:320,protein:"14g",carbs:"44g",fat:"8g",spice:"Mild",isNew:true},
  {id:"shahipaneer",name:"Shahi Paneer",price:340,badge:"VEG",region:"Mughlai",img:"images/shahi-paneer.jpg",emoji:"&#129472;",desc:"Paneer in luxurious saffron-infused cream and nut gravy. A Mughal royal recipe.",ingredients:["Paneer","Cashews","Almonds","Cream","Saffron","Cardamom","Rose water","Onion","Ginger","Garlic"],cal:460,protein:"16g",carbs:"20g",fat:"36g",spice:"Mild",isNew:true}
],
  nonveg:[
  {id:"bc",name:"Butter Chicken",price:420,badge:"NON-VEG",region:"Delhi",img:"images/butter-chicken.jpg",emoji:"&#127831;",desc:"Tandoor-grilled chicken in velvety tomato-cream sauce with fenugreek and aromatic spices.",ingredients:["Chicken","Tomato","Butter","Cream","Kasuri methi","Ginger","Garlic","Cardamom","Red chilli","Garam masala"],cal:480,protein:"36g",carbs:"16g",fat:"30g",spice:"Mild",isNew:false},
  {id:"rogan",name:"Mutton Rogan Josh",price:480,badge:"NON-VEG",region:"Kashmir",img:"images/rogan-josh.jpg",emoji:"&#129385;",desc:"Slow-braised Kashmiri mutton in aromatic gravy of fennel, dried ginger and whole spices.",ingredients:["Mutton","Kashmiri chilli","Fennel","Dry ginger","Cardamom","Cloves","Cinnamon","Mustard oil","Yoghurt","Onion"],cal:560,protein:"42g",carbs:"8g",fat:"38g",spice:"Hot",isNew:false},
  {id:"fish",name:"Kerala Fish Curry",price:420,badge:"NON-VEG",region:"Kerala",img:"images/fish-curry.jpg",emoji:"&#128031;",desc:"Fresh coastal fish in tangy coconut-tamarind gravy with curry leaves and raw mango.",ingredients:["Fish","Coconut milk","Tamarind","Raw mango","Curry leaves","Mustard seeds","Green chilli","Turmeric","Kokum","Coconut oil"],cal:410,protein:"38g",carbs:"14g",fat:"22g",spice:"Hot",isNew:false},
  {id:"cbiriyani",name:"Hyderabadi Chicken Biryani",price:380,badge:"NON-VEG",region:"Hyderabad",img:"images/chicken-biryani.jpg",emoji:"&#127859;",desc:"Slow dum-cooked biryani with bone-in chicken, kewra water and caramelised onions.",ingredients:["Basmati rice","Chicken","Saffron","Kewra water","Fried onions","Mint","Curd","Whole spices","Ghee","Green chilli"],cal:680,protein:"38g",carbs:"76g",fat:"24g",spice:"Medium",isNew:false},
  {id:"prawn",name:"Goan Prawn Masala",price:520,badge:"NON-VEG",region:"Goa",img:"images/prawn-masala.jpg",emoji:"&#129424;",desc:"Jumbo prawns in fiery Goan red masala with kokum, coconut vinegar and coastal spice blend.",ingredients:["Prawns","Coconut","Kokum","Coconut vinegar","Onion","Tomato","Red chilli","Turmeric","Mustard","Curry leaves"],cal:390,protein:"34g",carbs:"10g",fat:"24g",spice:"Hot",isNew:false},
  {id:"ctikkamasala",name:"Chicken Tikka Masala",price:400,badge:"NON-VEG",region:"Punjab",img:"images/chicken-tikka-masala.jpg",emoji:"&#127831;",desc:"Grilled chicken tikka simmered in spiced tomato cream sauce. Britain's favourite Indian dish.",ingredients:["Chicken","Tomato","Cream","Onion","Ginger","Garlic","Garam masala","Kasuri methi","Red chilli","Coriander"],cal:460,protein:"34g",carbs:"18g",fat:"28g",spice:"Medium",isNew:true},
  {id:"lambbiriyani",name:"Lamb Biryani",price:460,badge:"NON-VEG",region:"Mughlai",img:"images/lamb-biryani.jpg",emoji:"&#129385;",desc:"Slow-cooked tender lamb layered with saffron basmati rice. Sealed and cooked in dum.",ingredients:["Lamb","Basmati rice","Saffron","Fried onions","Mint","Curd","Cardamom","Cloves","Cinnamon","Rose water"],cal:720,protein:"44g",carbs:"72g",fat:"28g",spice:"Medium",isNew:true},
  {id:"chickenkorma",name:"Chicken Korma",price:380,badge:"NON-VEG",region:"Mughlai",img:"images/chicken-korma.jpg",emoji:"&#127831;",desc:"Chicken braised in fragrant yoghurt-nut sauce with saffron, cardamom and rose water.",ingredients:["Chicken","Cashews","Almonds","Yoghurt","Saffron","Cardamom","Onion","Cream","Rose water","Ghee"],cal:520,protein:"36g",carbs:"12g",fat:"36g",spice:"Mild",isNew:true},
  {id:"muttonkeema",name:"Mutton Keema",price:420,badge:"NON-VEG",region:"Delhi",img:"images/mutton-keema.jpg",emoji:"&#129385;",desc:"Spiced minced mutton cooked with green peas, tomatoes and aromatic masala. Delhi dhaba style.",ingredients:["Minced mutton","Green peas","Tomato","Onion","Ginger","Garlic","Garam masala","Coriander","Cumin","Oil"],cal:480,protein:"38g",carbs:"12g",fat:"32g",spice:"Hot",isNew:true},
  {id:"prawnbiriyani",name:"Prawn Biryani",price:480,badge:"NON-VEG",region:"Goa",img:"images/prawn-biryani.jpg",emoji:"&#129424;",desc:"Coastal Goan-style biryani with jumbo prawns, coconut rice and aromatic spices.",ingredients:["Prawns","Basmati rice","Coconut milk","Onion","Tomato","Green chilli","Curry leaves","Saffron","Ghee","Mint"],cal:620,protein:"36g",carbs:"70g",fat:"20g",spice:"Hot",isNew:true}
],
  desserts:[
  {id:"gulab",name:"Gulab Jamun",price:120,badge:"VEG",region:"North India",img:"images/gulab-jamun.jpg",emoji:"&#129361;",desc:"Soft khoya dumplings soaked in saffron-rose water sugar syrup.",ingredients:["Khoya","Maida","Baking soda","Ghee","Sugar syrup","Saffron","Rose water","Cardamom","Pistachios"],cal:320,protein:"6g",carbs:"46g",fat:"13g",spice:"None",isNew:false},
  {id:"rasmalai",name:"Rasmalai",price:160,badge:"VEG",region:"Bengal",img:"images/rasmalai.jpg",emoji:"&#129368;",desc:"Soft cottage cheese patties soaked in thickened saffron milk with pistachios and cardamom.",ingredients:["Chenna","Milk","Sugar","Saffron","Cardamom","Pistachios","Rose water","Almonds"],cal:280,protein:"10g",carbs:"38g",fat:"10g",spice:"None",isNew:false},
  {id:"kulfi",name:"Kulfi Falooda",price:180,badge:"VEG",region:"Old Delhi",img:"images/kulfi-falooda.jpg",emoji:"&#127846;",desc:"Pistachio kulfi over rose falooda noodles, basil seeds and cold milk.",ingredients:["Milk","Cream","Pistachios","Sugar","Cardamom","Falooda noodles","Rose syrup","Basil seeds"],cal:350,protein:"8g",carbs:"44g",fat:"16g",spice:"None",isNew:false},
  {id:"halwa",name:"Gajar Ka Halwa",price:140,badge:"VEG",region:"Punjab",img:"images/gajar-halwa.jpg",emoji:"&#129380;",desc:"Slow-cooked grated carrots in milk, sugar, ghee and cardamom. Topped with dry fruits.",ingredients:["Carrots","Milk","Ghee","Sugar","Cardamom","Cashews","Raisins","Almonds","Khoya"],cal:310,protein:"6g",carbs:"40g",fat:"14g",spice:"None",isNew:false},
  {id:"lassi",name:"Mango Lassi",price:120,badge:"VEG",region:"Punjab",img:"images/mango-lassi.jpg",emoji:"&#129389;",desc:"Thick Alphonso mango blended with creamy yoghurt, cardamom and a hint of saffron.",ingredients:["Alphonso mango","Yoghurt","Milk","Sugar","Cardamom","Saffron","Ice"],cal:240,protein:"6g",carbs:"38g",fat:"8g",spice:"None",isNew:false},
  {id:"kheer",name:"Rice Kheer",price:110,badge:"VEG",region:"North India",img:"images/rice-kheer.jpg",emoji:"&#127860;",desc:"Creamy slow-cooked rice pudding with saffron, cardamom, almonds and silver vark.",ingredients:["Basmati rice","Full-fat milk","Sugar","Saffron","Cardamom","Almonds","Pistachios","Rose water","Silver vark"],cal:280,protein:"7g",carbs:"44g",fat:"10g",spice:"None",isNew:true},
  {id:"jalebi",name:"Jalebi with Rabri",price:100,badge:"VEG",region:"Rajasthan",img:"images/jalebi-rabri.jpg",emoji:"&#127844;",desc:"Crispy fermented spiral jalebis dunked in sugar syrup, served with thick cold rabri.",ingredients:["Maida","Yoghurt","Saffron","Sugar syrup","Milk","Cardamom","Pistachios","Rose water"],cal:340,protein:"6g",carbs:"52g",fat:"12g",spice:"None",isNew:true},
  {id:"chai",name:"Masala Chai",price:60,badge:"VEG",region:"North India",img:"images/masala-chai.jpg",emoji:"&#127861;",desc:"Aromatic spiced tea brewed with ginger, cardamom, cinnamon and strong Assam tea leaves.",ingredients:["Assam tea","Milk","Ginger","Cardamom","Cinnamon","Black pepper","Cloves","Sugar"],cal:80,protein:"3g",carbs:"14g",fat:"3g",spice:"None",isNew:true},
  {id:"sharbat",name:"Rose Sharbat",price:90,badge:"VEG",region:"Lucknow",img:"images/rose-sharbat.jpg",emoji:"&#127861;",desc:"Chilled Rooh Afza rose syrup drink with basil seeds, lemon and cold water. Utterly refreshing.",ingredients:["Rose syrup","Basil seeds","Lemon","Chilled water","Ice","Mint"],cal:120,protein:"0g",carbs:"30g",fat:"0g",spice:"None",isNew:true},
  {id:"thandai",name:"Badam Thandai",price:130,badge:"VEG",region:"Rajasthan",img:"images/badam-thandai.jpg",emoji:"&#129379;",desc:"Chilled almond milk drink with saffron, cardamom, fennel and rose petals. Holi special.",ingredients:["Almonds","Milk","Fennel seeds","Poppy seeds","Cardamom","Saffron","Rose petals","Black pepper","Sugar","Ice"],cal:220,protein:"8g",carbs:"28g",fat:"9g",spice:"None",isNew:true}
]
};
window.ALL_DISHES = [...window.DISHES.starters,...window.DISHES.breads,...window.DISHES.veg,...window.DISHES.nonveg,...window.DISHES.desserts];
