// Clean Categorized Dishes — Veg, Non-Veg, Snacks, Drinks
window.DISHES = {
  "veg": [
    {
      "id": "masaladosa",
      "name": "Classic Masala Dosa",
      "price": 180,
      "badge": "VEG",
      "region": "Karnataka",
      "img": "images/masala-dosa.jpg",
      "emoji": "\ud83e\udd5e",
      "desc": "Crispy golden fermented rice & lentil crepe spread with spiced potato bhaji, cooked in pure ghee. Served with hot drumstick sambar and 2 fresh coconut chutneys.",
      "ingredients": [
        "Rice & urad dal batter",
        "Spiced potatoes",
        "Mustard seeds",
        "Curry leaves",
        "Turmeric",
        "Desi ghee",
        "Drumstick sambar",
        "Coconut chutney",
        "Tomato chutney"
      ],
      "cal": 340,
      "protein": "8g",
      "carbs": "52g",
      "fat": "12g",
      "spice": "Mild",
      "isNew": false,
      "category": "veg"
    },
    {
      "id": "mysoredosa",
      "name": "Mysore Masala Dosa",
      "price": 210,
      "badge": "VEG",
      "region": "Karnataka",
      "img": "images/mysore-masala-dosa.jpg",
      "emoji": "\ud83e\udd5e",
      "desc": "Crispy dosa layered with spicy red garlic-chilli paste, stuffed with potato masala and folded with a generous dollop of butter. Served with sambar.",
      "ingredients": [
        "Dosa batter",
        "Red garlic-chilli chutney",
        "Potato masala",
        "Amul butter",
        "Curry leaves",
        "Mustard seeds",
        "Sambar",
        "Coconut chutney"
      ],
      "cal": 390,
      "protein": "9g",
      "carbs": "54g",
      "fat": "16g",
      "spice": "Medium",
      "isNew": true,
      "category": "veg"
    },
    {
      "id": "idlisambar",
      "name": "Steamed Idli Sambar (3 pcs)",
      "price": 140,
      "badge": "VEG",
      "region": "Tamil Nadu",
      "img": "images/idli-sambar.jpg",
      "emoji": "\u26aa",
      "desc": "Pillow-soft, fluffy fermented rice cakes steamed fresh to order, served immersed in aromatic piping hot drumstick sambar and fresh coconut chutney.",
      "ingredients": [
        "Parboiled rice",
        "Urad dal",
        "Fenugreek seeds",
        "Toor dal",
        "Drumsticks",
        "Shallots",
        "Tamarind",
        "Sambar powder",
        "Coconut chutney"
      ],
      "cal": 210,
      "protein": "9g",
      "carbs": "44g",
      "fat": "2g",
      "spice": "Mild",
      "isNew": false,
      "category": "veg"
    },
    {
      "id": "meduvada",
      "name": "Crispy Medu Vada (2 pcs)",
      "price": 150,
      "badge": "VEG",
      "region": "Tamil Nadu",
      "img": "images/medu-vada.jpg",
      "emoji": "\ud83c\udf69",
      "desc": "Traditional doughnut-shaped lentil fritters, intensely crispy on the outside and pillowy soft inside, spiced with black peppercorns, ginger, and curry leaves.",
      "ingredients": [
        "Urad dal",
        "Crushed black pepper",
        "Ginger",
        "Curry leaves",
        "Green chillies",
        "Asafoetida (Hing)",
        "Coconut bits",
        "Sambar"
      ],
      "cal": 290,
      "protein": "11g",
      "carbs": "32g",
      "fat": "14g",
      "spice": "Mild",
      "isNew": false,
      "category": "veg"
    },
    {
      "id": "gkeepongal",
      "name": "Ghee Ven Pongal",
      "price": 190,
      "badge": "VEG",
      "region": "Tamil Nadu",
      "img": "images/ven-pongal.jpg",
      "emoji": "\ud83c\udf5a",
      "desc": "Comforting South Indian dish made of rice and yellow moong dal cooked to creamy perfection, tempered generously in pure ghee with roasted cashews and black pepper.",
      "ingredients": [
        "Raw rice",
        "Yellow moong dal",
        "Desi ghee",
        "Whole cashews",
        "Black peppercorns",
        "Cumin seeds",
        "Ginger",
        "Curry leaves",
        "Sambar"
      ],
      "cal": 380,
      "protein": "10g",
      "carbs": "56g",
      "fat": "14g",
      "spice": "Mild",
      "isNew": true,
      "category": "veg"
    },
    {
      "id": "pbm",
      "name": "Paneer Butter Masala",
      "price": 320,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/paneer-butter-masala.jpg",
      "emoji": "\ud83c\udf72",
      "desc": "Velvety tomato-cashew gravy with soft paneer cubes, infused with aromatic kasuri methi and finished with fresh cream and butter.",
      "ingredients": [
        "Fresh paneer",
        "Vine-ripened tomatoes",
        "Amul butter",
        "Fresh cream",
        "Cashew paste",
        "Ginger-garlic",
        "Kasuri methi",
        "Garam masala"
      ],
      "cal": 420,
      "protein": "16g",
      "carbs": "18g",
      "fat": "32g",
      "spice": "Mild",
      "isNew": false,
      "category": "veg"
    },
    {
      "id": "dalm",
      "name": "Dal Makhani (Overnight Simmered)",
      "price": 280,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/dal-makhani.jpg",
      "emoji": "\ud83c\udf72",
      "desc": "Whole black lentils and kidney beans slow-cooked for 16 hours over charcoal tandoor with tomato puree, white butter, and fresh cream.",
      "ingredients": [
        "Urad sabut (Black lentils)",
        "Rajma (Kidney beans)",
        "White butter",
        "Fresh cream",
        "Tomato puree",
        "Ginger",
        "Garlic",
        "Degi mirch"
      ],
      "cal": 390,
      "protein": "14g",
      "carbs": "34g",
      "fat": "20g",
      "spice": "Mild",
      "isNew": false,
      "category": "veg"
    },
    {
      "id": "palak",
      "name": "Palak Paneer",
      "price": 300,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/palak-paneer.jpg",
      "emoji": "\ud83e\udd6c",
      "desc": "Fresh blanched spinach puree tempered with garlic, cumin, and mild spices, gently simmered with soft cottage cheese cubes.",
      "ingredients": [
        "Fresh spinach",
        "Paneer",
        "Garlic",
        "Cumin",
        "Green chillies",
        "Ginger",
        "Fresh cream",
        "Kasuri methi",
        "Garam masala"
      ],
      "cal": 360,
      "protein": "15g",
      "carbs": "14g",
      "fat": "26g",
      "spice": "Mild",
      "isNew": false,
      "category": "veg"
    },
    {
      "id": "kadaipaneer",
      "name": "Kadai Paneer",
      "price": 310,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/kadai-paneer.jpg",
      "emoji": "\ud83e\udd58",
      "desc": "Cottage cheese cubes and crunchy bell peppers tossed with freshly pounded coriander seeds and dry red chillies in an iron kadai gravy.",
      "ingredients": [
        "Paneer",
        "Bell peppers (Capsicum)",
        "Onion petals",
        "Tomatoes",
        "Whole coriander seeds",
        "Dry Kashmiri chillies",
        "Ginger",
        "Kasuri methi"
      ],
      "cal": 350,
      "protein": "14g",
      "carbs": "16g",
      "fat": "22g",
      "spice": "Medium",
      "isNew": false,
      "category": "veg"
    },
    {
      "id": "malaikofta",
      "name": "Shahi Malai Kofta",
      "price": 340,
      "badge": "VEG",
      "region": "Mughlai",
      "img": "images/malai-kofta.jpg",
      "emoji": "\ud83c\udf72",
      "desc": "Melt-in-mouth dumplings of paneer, khoya and dry fruits fried golden and served in a luxurious, creamy cashew-onion white gravy.",
      "ingredients": [
        "Paneer",
        "Khoya",
        "Cashews",
        "Raisins",
        "Cardamom",
        "Cashew nut paste",
        "Fresh cream",
        "Onion puree",
        "Saffron",
        "Rose water"
      ],
      "cal": 460,
      "protein": "13g",
      "carbs": "26g",
      "fat": "34g",
      "spice": "Mild",
      "isNew": true,
      "category": "veg"
    },
    {
      "id": "chana",
      "name": "Pindi Chana Masala",
      "price": 260,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/chana-masala.jpg",
      "emoji": "\ud83e\udd58",
      "desc": "Amritsari style dark chickpeas boiled with black tea leaves, tossed in aromatic dry spices, pomegranate seeds (anardana), and amchur.",
      "ingredients": [
        "Kabuli chickpeas",
        "Anardana (Pomegranate powder)",
        "Amchur",
        "Black tea infusion",
        "Ginger juliennes",
        "Slit green chillies",
        "Ghee",
        "Garam masala"
      ],
      "cal": 340,
      "protein": "14g",
      "carbs": "46g",
      "fat": "10g",
      "spice": "Medium",
      "isNew": false,
      "category": "veg"
    },
    {
      "id": "sarsonkasaag",
      "name": "Sarson Ka Saag (with Makki Roti)",
      "price": 310,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/sarson-saag.jpg",
      "emoji": "\ud83e\udd6c",
      "desc": "Authentic winter Punjabi mustard greens slow-cooked with bathua, spinach, and makki atta, tempered with ginger and desi ghee. Served with 2 Makki Roti and jaggery.",
      "ingredients": [
        "Mustard leaves (Sarson)",
        "Bathua",
        "Spinach",
        "Cornmeal (Makki atta)",
        "Ginger",
        "Garlic",
        "Green chillies",
        "Desi ghee",
        "Makki roti",
        "Gud (Jaggery)"
      ],
      "cal": 440,
      "protein": "12g",
      "carbs": "52g",
      "fat": "20g",
      "spice": "Medium",
      "isNew": true,
      "category": "veg"
    },
    {
      "id": "vbiriyani",
      "name": "Hyderabadi Veg Dum Biryani",
      "price": 340,
      "badge": "VEG",
      "region": "Hyderabad",
      "img": "images/veg-biryani.jpg",
      "emoji": "\ud83c\udf5a",
      "desc": "Fragrant basmati rice layered with seasonal vegetables, saffron, mint, and fried onions, slow-cooked in handi sealed with dough.",
      "ingredients": [
        "Basmati rice",
        "French beans",
        "Carrots",
        "Cauliflower",
        "Paneer",
        "Saffron",
        "Fried onions",
        "Mint",
        "Curd",
        "Ghee"
      ],
      "cal": 520,
      "protein": "10g",
      "carbs": "80g",
      "fat": "18g",
      "spice": "Medium",
      "isNew": false,
      "category": "veg"
    },
    {
      "id": "curdrice",
      "name": "Temple Style Curd Rice",
      "price": 160,
      "badge": "VEG",
      "region": "Tamil Nadu",
      "img": "images/curd-rice.jpg",
      "emoji": "\ud83c\udf5a",
      "desc": "Creamy soft cooked rice blended with fresh homemade curd and milk, tempered with mustard seeds, curry leaves, ginger, green chillies, and topped with pomegranate pearls.",
      "ingredients": [
        "Soft cooked rice",
        "Fresh thick curd",
        "Milk",
        "Mustard seeds",
        "Curry leaves",
        "Ginger",
        "Green chillies",
        "Hing",
        "Pomegranate seeds"
      ],
      "cal": 260,
      "protein": "8g",
      "carbs": "42g",
      "fat": "7g",
      "spice": "Mild",
      "isNew": false,
      "category": "veg"
    },
    {
      "id": "garlicnaan",
      "name": "Garlic Butter Naan",
      "price": 80,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/garlic-naan.jpg",
      "emoji": "\ud83e\uded3",
      "desc": "Soft leavened flatbread baked in clay tandoor, topped with minced garlic, fresh coriander, and brushed with melted butter.",
      "ingredients": [
        "Refined flour",
        "Milk",
        "Curd",
        "Fresh garlic",
        "Amul butter",
        "Coriander",
        "Yeast",
        "Nigella seeds (Kalonji)"
      ],
      "cal": 260,
      "protein": "7g",
      "carbs": "40g",
      "fat": "9g",
      "spice": "None",
      "isNew": false,
      "category": "veg"
    },
    {
      "id": "amritsarikulcha",
      "name": "Amritsari Aloo Kulcha",
      "price": 120,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/stuffed-kulcha.jpg",
      "emoji": "\ud83e\uded3",
      "desc": "Crispy layered tandoor-baked bread stuffed with spiced mashed potatoes, onions, anardana, and green chillies, topped with butter.",
      "ingredients": [
        "Maida",
        "Boiled potatoes",
        "Anardana (Pomegranate seeds)",
        "Chopped onions",
        "Ajwain",
        "Green chillies",
        "Amul butter"
      ],
      "cal": 290,
      "protein": "9g",
      "carbs": "42g",
      "fat": "10g",
      "spice": "Mild",
      "isNew": false,
      "category": "veg"
    }
  ],
  "nonveg": [
    {
      "id": "bc",
      "name": "Old Delhi Butter Chicken",
      "price": 420,
      "badge": "NON-VEG",
      "region": "Delhi",
      "img": "images/butter-chicken.jpg",
      "emoji": "\ud83c\udf57",
      "desc": "Tandoor-charred chicken pieces simmered in silky smooth, mildly spiced tomato gravy with honey, butter, fenugreek, and cream.",
      "ingredients": [
        "Tandoori chicken",
        "Vine-ripened tomatoes",
        "Butter",
        "Fresh cream",
        "Kasuri methi",
        "Ginger-garlic",
        "Kashmiri chilli",
        "Cardamom",
        "Honey"
      ],
      "cal": 480,
      "protein": "36g",
      "carbs": "16g",
      "fat": "30g",
      "spice": "Mild",
      "isNew": false,
      "category": "nonveg"
    },
    {
      "id": "cbiriyani",
      "name": "Hyderabadi Chicken Dum Biryani",
      "price": 380,
      "badge": "NON-VEG",
      "region": "Hyderabad",
      "img": "images/chicken-biryani.jpg",
      "emoji": "\ud83c\udf57",
      "desc": "Authentic Kachchi Dum Biryani: tender bone-in chicken marinated overnight in spices and curd, slow-cooked in handi layered with fragrant saffron basmati rice.",
      "ingredients": [
        "Aged basmati rice",
        "Bone-in chicken",
        "Saffron",
        "Caramelised onions (Birista)",
        "Mint leaves",
        "Curd",
        "Shahi jeera",
        "Ghee",
        "Kewra water"
      ],
      "cal": 680,
      "protein": "38g",
      "carbs": "76g",
      "fat": "24g",
      "spice": "Medium",
      "isNew": false,
      "category": "nonveg"
    },
    {
      "id": "rogan",
      "name": "Mutton Rogan Josh",
      "price": 480,
      "badge": "NON-VEG",
      "region": "Kashmir",
      "img": "images/rogan-josh.jpg",
      "emoji": "\ud83e\udd69",
      "desc": "Succulent chunks of bone-in mutton slow-braised in an aromatic crimson gravy infused with Kashmiri red chillies, fennel powder, and mawal flowers.",
      "ingredients": [
        "Tender goat meat",
        "Mustard oil",
        "Kashmiri red chillies",
        "Fennel powder (Saunf)",
        "Dry ginger (Sonth)",
        "Black cardamom",
        "Cinnamon",
        "Whisked curd"
      ],
      "cal": 560,
      "protein": "42g",
      "carbs": "8g",
      "fat": "38g",
      "spice": "Hot",
      "isNew": false,
      "category": "nonveg"
    },
    {
      "id": "chettinadchicken",
      "name": "Chettinad Spicy Chicken Curry",
      "price": 410,
      "badge": "NON-VEG",
      "region": "Tamil Nadu",
      "img": "images/chettinad-chicken.jpg",
      "emoji": "\ud83c\udf57",
      "desc": "Fiery Tamil Nadu delicacy: chicken braised in freshly roasted black pepper, kalpasi (stone flower), star anise, fennel, and grated coconut paste.",
      "ingredients": [
        "Country chicken",
        "Black peppercorns",
        "Kalpasi (Stone flower)",
        "Star anise",
        "Fennel seeds",
        "Shallots",
        "Curry leaves",
        "Grated coconut",
        "Sesame oil"
      ],
      "cal": 450,
      "protein": "38g",
      "carbs": "10g",
      "fat": "28g",
      "spice": "Hot",
      "isNew": true,
      "category": "nonveg"
    },
    {
      "id": "fish",
      "name": "Kerala Malabar Fish Curry",
      "price": 420,
      "badge": "NON-VEG",
      "region": "Kerala",
      "img": "images/fish-curry.jpg",
      "emoji": "\ud83d\udc1f",
      "desc": "Fresh kingfish steaks cooked in earthen clay pots with thick coconut milk, tangy Kodampuli (Malabar kokum), shallots, and fragrant curry leaves.",
      "ingredients": [
        "Kingfish fillets",
        "Kodampuli (Malabar tamarind)",
        "Thick coconut milk",
        "Shallots",
        "Ginger & garlic",
        "Fenugreek seeds",
        "Curry leaves",
        "Coconut oil"
      ],
      "cal": 410,
      "protein": "38g",
      "carbs": "14g",
      "fat": "22g",
      "spice": "Hot",
      "isNew": false,
      "category": "nonveg"
    },
    {
      "id": "prawn",
      "name": "Goan Prawn Masala",
      "price": 520,
      "badge": "NON-VEG",
      "region": "Goa",
      "img": "images/prawn-masala.jpg",
      "emoji": "\ud83e\udd90",
      "desc": "Jumbo tiger prawns simmered in vibrant Goan peri-peri spiced red gravy with coconut vinegar, garlic, and freshly ground whole coastal spices.",
      "ingredients": [
        "Tiger prawns",
        "Kashmiri red chillies",
        "Toddy vinegar",
        "Garlic",
        "Cinnamon",
        "Cloves",
        "Cumin",
        "Onions",
        "Tomatoes",
        "Coconut oil"
      ],
      "cal": 390,
      "protein": "34g",
      "carbs": "10g",
      "fat": "24g",
      "spice": "Hot",
      "isNew": false,
      "category": "nonveg"
    },
    {
      "id": "andhrachicken",
      "name": "Andhra Kodi Vepudu (Spicy Chicken Fry)",
      "price": 390,
      "badge": "NON-VEG",
      "region": "Andhra Pradesh",
      "img": "images/andhra-chicken-fry.jpg",
      "emoji": "\ud83c\udf57",
      "desc": "Dry-roasted spicy Andhra chicken tossed on high flame with Guntur red chillies, crushed black pepper, fresh curry leaves, and caramelized shallots.",
      "ingredients": [
        "Chicken pieces",
        "Guntur dry red chillies",
        "Crushed black pepper",
        "Coriander seeds",
        "Curry leaves",
        "Shallots",
        "Ginger-garlic",
        "Lemon juice"
      ],
      "cal": 430,
      "protein": "40g",
      "carbs": "8g",
      "fat": "26g",
      "spice": "Hot",
      "isNew": true,
      "category": "nonveg"
    },
    {
      "id": "laalmaas",
      "name": "Rajasthani Royal Laal Maas",
      "price": 490,
      "badge": "NON-VEG",
      "region": "Rajasthan",
      "img": "images/laal-maas.jpg",
      "emoji": "\ud83e\udd69",
      "desc": "Heritage warrior dish of Rajasthan: tender goat meat cooked with pungent Mathania red chillies, garlic paste, and pure ghee with smoky charcoal aroma (dhungar).",
      "ingredients": [
        "Mutton chunks",
        "Mathania red chillies",
        "Garlic paste",
        "Desi ghee",
        "Curd",
        "Cloves",
        "Cardamom",
        "Kachri powder",
        "Charcoal smoke"
      ],
      "cal": 580,
      "protein": "44g",
      "carbs": "6g",
      "fat": "42g",
      "spice": "Hot",
      "isNew": true,
      "category": "nonveg"
    },
    {
      "id": "ctikkamasala",
      "name": "Chicken Tikka Masala",
      "price": 400,
      "badge": "NON-VEG",
      "region": "Punjab",
      "img": "images/chicken-tikka-masala.jpg",
      "emoji": "\ud83c\udf57",
      "desc": "Smoky char-grilled chicken tikka basted in spiced tandoori marinade, then tossed into a rich, robust onion-tomato masala gravy with capsicum.",
      "ingredients": [
        "Chicken tikka",
        "Onion-tomato gravy",
        "Capsicum",
        "Ginger",
        "Garlic",
        "Garam masala",
        "Kasuri methi",
        "Fresh cream",
        "Coriander"
      ],
      "cal": 460,
      "protein": "34g",
      "carbs": "18g",
      "fat": "28g",
      "spice": "Medium",
      "isNew": false,
      "category": "nonveg"
    },
    {
      "id": "lambbiriyani",
      "name": "Lucknowi Lamb Dum Biryani",
      "price": 460,
      "badge": "NON-VEG",
      "region": "Awadh",
      "img": "images/lamb-biryani.jpg",
      "emoji": "\ud83e\udd69",
      "desc": "Royal Awadhi Pakki Biryani: succulent tender lamb cooked in aromatic yakhni stock, layered with perfumed basmati rice, saffron milk, and ittar.",
      "ingredients": [
        "Lamb meat",
        "Aged basmati rice",
        "Lamb bone broth (Yakhni)",
        "Saffron",
        "Rose water & ittar",
        "Desi ghee",
        "Cardamom & mace",
        "Fried onions"
      ],
      "cal": 720,
      "protein": "44g",
      "carbs": "72g",
      "fat": "28g",
      "spice": "Medium",
      "isNew": false,
      "category": "nonveg"
    },
    {
      "id": "ctikka",
      "name": "Chicken Malai Tikka",
      "price": 380,
      "badge": "NON-VEG",
      "region": "Mughlai",
      "img": "images/chicken-tikka.jpg",
      "emoji": "\ud83c\udf57",
      "desc": "Tender chicken chunks marinated in heavy cream, hung curd, cashew paste and mild white pepper, grilled on skewers in tandoor.",
      "ingredients": [
        "Boneless chicken",
        "Fresh cream",
        "Cashew paste",
        "Hung curd",
        "Ginger-garlic",
        "Cardamom powder",
        "White pepper",
        "Butter"
      ],
      "cal": 420,
      "protein": "34g",
      "carbs": "6g",
      "fat": "29g",
      "spice": "Mild",
      "isNew": false,
      "category": "nonveg"
    },
    {
      "id": "fishamritsari",
      "name": "Fish Amritsari Fry",
      "price": 360,
      "badge": "NON-VEG",
      "region": "Punjab",
      "img": "images/fish-amritsari.jpg",
      "emoji": "\ud83d\udc1f",
      "desc": "Fresh boneless fish fillets marinated in carom seeds (ajwain), ginger-garlic, and lemon juice, dipped in gram flour batter and fried crispy golden.",
      "ingredients": [
        "Fish fillets",
        "Besan (Gram flour)",
        "Ajwain",
        "Ginger-garlic paste",
        "Kashmiri red chilli",
        "Lemon juice",
        "Chaat masala",
        "Mustard oil"
      ],
      "cal": 390,
      "protein": "28g",
      "carbs": "18g",
      "fat": "22g",
      "spice": "Hot",
      "isNew": false,
      "category": "nonveg"
    }
  ],
  "snacks": [
    {
      "id": "samosa",
      "name": "Samosa Chaat",
      "price": 180,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/samosa.jpg",
      "emoji": "\ud83e\udd5f",
      "desc": "Crispy golden samosas crushed and topped with spiced chole, sweet tamarind, tangy mint chutneys, chilled curd and crunchy sev.",
      "ingredients": [
        "Wheat flour",
        "Potato",
        "Green peas",
        "Kabuli chana",
        "Tamarind chutney",
        "Mint chutney",
        "Curd",
        "Sev",
        "Chaat masala",
        "Pomegranate"
      ],
      "cal": 310,
      "protein": "8g",
      "carbs": "42g",
      "fat": "11g",
      "spice": "Medium",
      "isNew": false,
      "category": "snacks"
    },
    {
      "id": "panipuri",
      "name": "Pani Puri / Golgappe (8 pcs)",
      "price": 140,
      "badge": "VEG",
      "region": "Delhi",
      "img": "images/pani-puri.jpg",
      "emoji": "\ud83e\udd5f",
      "desc": "Crispy hollow semolina puris filled with spiced potato-chickpea mix, tangy hing-jeera water, and sweet dates-tamarind chutney.",
      "ingredients": [
        "Semolina puris",
        "Boiled potatoes",
        "Black chickpeas",
        "Mint & coriander water",
        "Tamarind chutney",
        "Black salt",
        "Hing",
        "Roasted cumin"
      ],
      "cal": 180,
      "protein": "4g",
      "carbs": "36g",
      "fat": "3g",
      "spice": "Hot",
      "isNew": true,
      "category": "snacks"
    },
    {
      "id": "pavbhaji",
      "name": "Amul Butter Pav Bhaji",
      "price": 220,
      "badge": "VEG",
      "region": "Mumbai",
      "img": "images/pav-bhaji.jpg",
      "emoji": "\ud83c\udf5b",
      "desc": "Spiced mashed vegetable curry slow-simmered on a giant tawa with secret Mumbai spices, topped with generous Amul butter, served with soft toasted pav.",
      "ingredients": [
        "Potatoes",
        "Cauliflower",
        "Green peas",
        "Tomatoes",
        "Capsicum",
        "Amul butter",
        "Pav bhaji masala",
        "Kasuri methi",
        "Pav bread",
        "Lemon & onion"
      ],
      "cal": 450,
      "protein": "11g",
      "carbs": "58g",
      "fat": "20g",
      "spice": "Medium",
      "isNew": true,
      "category": "snacks"
    },
    {
      "id": "vadapav",
      "name": "Mumbai Vada Pav (2 pcs)",
      "price": 120,
      "badge": "VEG",
      "region": "Mumbai",
      "img": "images/vada-pav.jpg",
      "emoji": "\ud83c\udf54",
      "desc": "Iconic spiced potato fritter coated in golden gram flour, tucked inside soft pav with spicy garlic dry chutney, fried green chillies, and sweet tamarind sauce.",
      "ingredients": [
        "Potatoes",
        "Gram flour (Besan)",
        "Mustard seeds",
        "Curry leaves",
        "Garlic dry chutney",
        "Green chillies",
        "Pav bread",
        "Turmeric"
      ],
      "cal": 320,
      "protein": "7g",
      "carbs": "44g",
      "fat": "13g",
      "spice": "Hot",
      "isNew": true,
      "category": "snacks"
    },
    {
      "id": "dahipuri",
      "name": "Dahi Puri Supreme",
      "price": 160,
      "badge": "VEG",
      "region": "Mumbai",
      "img": "images/dahi-puri.jpg",
      "emoji": "\ud83e\udd63",
      "desc": "Crispy puris stuffed with boiled potato cubes and moong sprouts, drenched in sweet whipped yoghurt, tamarind glaze, green chutney, and fine nylon sev.",
      "ingredients": [
        "Puri",
        "Boiled potato",
        "Sprouted moong",
        "Sweet curd",
        "Tamarind chutney",
        "Mint chutney",
        "Nylon sev",
        "Pomegranate",
        "Chaat masala"
      ],
      "cal": 240,
      "protein": "6g",
      "carbs": "36g",
      "fat": "8g",
      "spice": "Mild",
      "isNew": false,
      "category": "snacks"
    },
    {
      "id": "bhelpuri",
      "name": "Chowpatty Bhel Puri",
      "price": 130,
      "badge": "VEG",
      "region": "Mumbai",
      "img": "images/bhel-puri.jpg",
      "emoji": "\ud83e\udd57",
      "desc": "Light puffed rice tossed with roasted peanuts, crushed papdi, diced onions, tomatoes, raw mango, fresh coriander, and sweet-spicy chutneys.",
      "ingredients": [
        "Puffed rice (Kurmura)",
        "Nylon sev",
        "Papdi",
        "Roasted peanuts",
        "Onion",
        "Tomato",
        "Raw mango",
        "Tamarind chutney",
        "Chilli chutney",
        "Lemon"
      ],
      "cal": 190,
      "protein": "5g",
      "carbs": "35g",
      "fat": "4g",
      "spice": "Medium",
      "isNew": true,
      "category": "snacks"
    },
    {
      "id": "onionpakoda",
      "name": "Crispy Kanda / Onion Pakoda",
      "price": 150,
      "badge": "VEG",
      "region": "Maharashtra",
      "img": "images/onion-pakoda.jpg",
      "emoji": "\ud83e\uddc5",
      "desc": "Thinly sliced red onions tossed with ajwain, green chillies, fresh coriander and besan, deep-fried extra crunchy. Perfect snack with mint chutney.",
      "ingredients": [
        "Red onions",
        "Besan (Gram flour)",
        "Rice flour",
        "Ajwain (Carom seeds)",
        "Green chillies",
        "Coriander",
        "Red chilli powder",
        "Hing",
        "Oil"
      ],
      "cal": 280,
      "protein": "6g",
      "carbs": "30g",
      "fat": "15g",
      "spice": "Medium",
      "isNew": true,
      "category": "snacks"
    },
    {
      "id": "mirchibajji",
      "name": "Andhra Mirchi Bajji (4 pcs)",
      "price": 160,
      "badge": "VEG",
      "region": "Andhra Pradesh",
      "img": "images/mirchi-bajji.jpg",
      "emoji": "\ud83c\udf36\ufe0f",
      "desc": "Large Bhavnagri green chillies stuffed with tangy ajwain-tamarind paste, dipped in spiced chickpea batter, fried golden and cut open with chopped onion and chaat masala.",
      "ingredients": [
        "Large green chillies",
        "Besan",
        "Tamarind pulp",
        "Ajwain",
        "Cumin",
        "Chopped onions",
        "Lemon juice",
        "Chaat masala",
        "Oil"
      ],
      "cal": 260,
      "protein": "7g",
      "carbs": "28g",
      "fat": "14g",
      "spice": "Hot",
      "isNew": true,
      "category": "snacks"
    },
    {
      "id": "paneerpakoda",
      "name": "Amritsari Paneer Pakoda",
      "price": 240,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/paneer-pakoda.jpg",
      "emoji": "\ud83e\uddc0",
      "desc": "Thick slices of malai paneer sandwiched with tangy mint-chutney, dipped in spiced ajwain-besan batter, and fried golden. Melting interior.",
      "ingredients": [
        "Malai paneer",
        "Besan",
        "Ajwain",
        "Mint chutney",
        "Kasuri methi",
        "Chaat masala",
        "Red chilli",
        "Ginger-garlic paste",
        "Oil"
      ],
      "cal": 380,
      "protein": "18g",
      "carbs": "16g",
      "fat": "27g",
      "spice": "Mild",
      "isNew": true,
      "category": "snacks"
    },
    {
      "id": "harabharakabab",
      "name": "Hara Bhara Kabab",
      "price": 260,
      "badge": "VEG",
      "region": "Delhi",
      "img": "images/hara-bhara-kabab.jpg",
      "emoji": "\ud83e\udd6c",
      "desc": "Vibrant emerald patties made with spinach, green peas, mashed potatoes and cottage cheese, scented with cardamom and topped with cashew nut.",
      "ingredients": [
        "Fresh spinach",
        "Green peas",
        "Paneer",
        "Potato",
        "Ginger",
        "Green chilli",
        "Cashew nut",
        "Cardamom",
        "Chaat masala",
        "Cornflour"
      ],
      "cal": 230,
      "protein": "10g",
      "carbs": "24g",
      "fat": "10g",
      "spice": "Mild",
      "isNew": false,
      "category": "snacks"
    },
    {
      "id": "alootikki",
      "name": "Crispy Aloo Tikki Chaat",
      "price": 160,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/aloo-tikki.jpg",
      "emoji": "\ud83e\udd54",
      "desc": "Golden fried spiced potato patties topped with warm kabuli chana, sweet tamarind chutney, green mint sauce, whisked curd, and fresh ginger juliennes.",
      "ingredients": [
        "Boiled potatoes",
        "Green peas",
        "Cornflour",
        "Cumin",
        "Ginger",
        "Chana masala",
        "Curd",
        "Tamarind chutney",
        "Mint chutney",
        "Chaat masala"
      ],
      "cal": 290,
      "protein": "6g",
      "carbs": "44g",
      "fat": "10g",
      "spice": "Medium",
      "isNew": false,
      "category": "snacks"
    }
  ],
  "drinks": [
    {
      "id": "lassi",
      "name": "Royal Mango Lassi",
      "price": 120,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/mango-lassi.jpg",
      "emoji": "\ud83e\udd6d",
      "desc": "Thick chilled sweet yoghurt blended with real Ratnagiri Alphonso mango pulp, green cardamom, and garnished with saffron strands and pistachios.",
      "ingredients": [
        "Alphonso mango pulp",
        "Thick sweet curd",
        "Fresh cream",
        "Cardamom powder",
        "Saffron",
        "Pistachios"
      ],
      "cal": 240,
      "protein": "6g",
      "carbs": "38g",
      "fat": "8g",
      "spice": "None",
      "isNew": false,
      "category": "drinks"
    },
    {
      "id": "filtercoffee",
      "name": "Madras Degree Filter Coffee",
      "price": 80,
      "badge": "VEG",
      "region": "Tamil Nadu",
      "img": "images/filter-coffee.jpg",
      "emoji": "\u2615",
      "desc": "Authentic South Indian decoction brewed with fresh dark roast chicory coffee beans and foamy boiled full-fat milk in traditional brass davarah and tumbler.",
      "ingredients": [
        "80:20 Plantation coffee & chicory blend",
        "Full-fat milk",
        "Sugar"
      ],
      "cal": 110,
      "protein": "4g",
      "carbs": "16g",
      "fat": "4g",
      "spice": "None",
      "isNew": true,
      "category": "drinks"
    },
    {
      "id": "chai",
      "name": "Kadak Masala Chai",
      "price": 60,
      "badge": "VEG",
      "region": "North India",
      "img": "images/masala-chai.jpg",
      "emoji": "\u2615",
      "desc": "Strong Assam tea brewed with crushed ginger, green cardamom, cinnamon, cloves, black pepper, and fresh whole milk. Served piping hot.",
      "ingredients": [
        "Assam CTC tea",
        "Fresh milk",
        "Crushed ginger",
        "Green cardamom",
        "Cinnamon",
        "Cloves",
        "Black pepper",
        "Sugar"
      ],
      "cal": 80,
      "protein": "3g",
      "carbs": "14g",
      "fat": "3g",
      "spice": "None",
      "isNew": false,
      "category": "drinks"
    },
    {
      "id": "sweetlassi",
      "name": "Punjabi Malai Sweet Lassi",
      "price": 110,
      "badge": "VEG",
      "region": "Punjab",
      "img": "images/sweet-lassi.jpg",
      "emoji": "\ud83e\udd5b",
      "desc": "Hand-churned creamy thick yoghurt drink flavored with fragrant rose water and cardamom, topped with thick clotted malai and crushed almonds.",
      "ingredients": [
        "Fresh thick curd",
        "Sugar",
        "Rose water",
        "Cardamom",
        "Fresh malai (Cream)",
        "Almonds",
        "Pistachios"
      ],
      "cal": 260,
      "protein": "7g",
      "carbs": "36g",
      "fat": "10g",
      "spice": "None",
      "isNew": true,
      "category": "drinks"
    },
    {
      "id": "rose_sharbat",
      "name": "Old Delhi Rose Sharbat with Sabja",
      "price": 90,
      "badge": "VEG",
      "region": "Lucknow",
      "img": "images/rose-sharbat.jpg",
      "emoji": "\ud83c\udf39",
      "desc": "Chilled traditional Rooh Afza rose cordial infused with soaked basil seeds (sabja), a squeeze of fresh lime, and crushed mint leaves.",
      "ingredients": [
        "Rooh Afza rose syrup",
        "Soaked sabja (Basil seeds)",
        "Fresh lime juice",
        "Chilled water",
        "Mint sprigs",
        "Ice"
      ],
      "cal": 120,
      "protein": "0g",
      "carbs": "30g",
      "fat": "0g",
      "spice": "None",
      "isNew": false,
      "category": "drinks"
    },
    {
      "id": "masala_chaas",
      "name": "Masala Buttermilk (Chaas)",
      "price": 70,
      "badge": "VEG",
      "region": "Gujarat",
      "img": "images/masala-chaas.jpg",
      "emoji": "\ud83e\udd5b",
      "desc": "Refreshing chilled buttermilk churned with roasted cumin powder, black salt, grated ginger, green chillies, fresh coriander, and curry leaves.",
      "ingredients": [
        "Fresh churned curd",
        "Roasted cumin (Bhuna jeera)",
        "Kala namak (Black salt)",
        "Ginger",
        "Green chilli",
        "Coriander",
        "Curry leaves"
      ],
      "cal": 65,
      "protein": "3g",
      "carbs": "6g",
      "fat": "3g",
      "spice": "Mild",
      "isNew": true,
      "category": "drinks"
    },
    {
      "id": "gulab",
      "name": "Royal Shahi Gulab Jamun (2 pcs)",
      "price": 120,
      "badge": "VEG",
      "region": "North India",
      "img": "images/gulab-jamun.jpg",
      "emoji": "\ud83c\udf6f",
      "desc": "Golden fried khoya dumplings infused with saffron and pistachios, soaked warm in rosewater-cardamom sugar syrup.",
      "ingredients": [
        "Fresh khoya (Mawa)",
        "Chhena",
        "Cardamom",
        "Rose water",
        "Saffron (Kesar)",
        "Pistachios",
        "Sugar syrup",
        "Desi ghee"
      ],
      "cal": 320,
      "protein": "6g",
      "carbs": "46g",
      "fat": "13g",
      "spice": "None",
      "isNew": false,
      "category": "drinks"
    },
    {
      "id": "rasmalai",
      "name": "Kesar Pista Rasmalai (2 pcs)",
      "price": 160,
      "badge": "VEG",
      "region": "Bengal",
      "img": "images/rasmalai.jpg",
      "emoji": "\ud83e\udd5b",
      "desc": "Spongy cottage cheese patties poached in sugar syrup and steeped in chilled, thickened saffron milk topped with sliced pistachios and almonds.",
      "ingredients": [
        "Chhena (Cottage cheese)",
        "Full-cream milk",
        "Kashmiri saffron",
        "Cardamom",
        "Pistachios",
        "Almonds",
        "Sugar"
      ],
      "cal": 280,
      "protein": "10g",
      "carbs": "38g",
      "fat": "10g",
      "spice": "None",
      "isNew": false,
      "category": "drinks"
    },
    {
      "id": "kulfi",
      "name": "Old Delhi Kulfi Falooda",
      "price": 180,
      "badge": "VEG",
      "region": "Old Delhi",
      "img": "images/kulfi-falooda.jpg",
      "emoji": "\ud83c\udf68",
      "desc": "Dense, traditional malai kulfi sliced and served over chilled cornstarch falooda vermicelli, rose syrup, and blooming sabja seeds.",
      "ingredients": [
        "Traditional malai kulfi",
        "Falooda sev",
        "Rooh Afza rose syrup",
        "Sabja (Basil seeds)",
        "Pistachios",
        "Rabri"
      ],
      "cal": 350,
      "protein": "8g",
      "carbs": "44g",
      "fat": "16g",
      "spice": "None",
      "isNew": false,
      "category": "drinks"
    }
  ]
};
window.ALL_DISHES = [
  {
    "id": "masaladosa",
    "name": "Classic Masala Dosa",
    "price": 180,
    "badge": "VEG",
    "region": "Karnataka",
    "img": "images/masala-dosa.jpg",
    "emoji": "\ud83e\udd5e",
    "desc": "Crispy golden fermented rice & lentil crepe spread with spiced potato bhaji, cooked in pure ghee. Served with hot drumstick sambar and 2 fresh coconut chutneys.",
    "ingredients": [
      "Rice & urad dal batter",
      "Spiced potatoes",
      "Mustard seeds",
      "Curry leaves",
      "Turmeric",
      "Desi ghee",
      "Drumstick sambar",
      "Coconut chutney",
      "Tomato chutney"
    ],
    "cal": 340,
    "protein": "8g",
    "carbs": "52g",
    "fat": "12g",
    "spice": "Mild",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "mysoredosa",
    "name": "Mysore Masala Dosa",
    "price": 210,
    "badge": "VEG",
    "region": "Karnataka",
    "img": "images/mysore-masala-dosa.jpg",
    "emoji": "\ud83e\udd5e",
    "desc": "Crispy dosa layered with spicy red garlic-chilli paste, stuffed with potato masala and folded with a generous dollop of butter. Served with sambar.",
    "ingredients": [
      "Dosa batter",
      "Red garlic-chilli chutney",
      "Potato masala",
      "Amul butter",
      "Curry leaves",
      "Mustard seeds",
      "Sambar",
      "Coconut chutney"
    ],
    "cal": 390,
    "protein": "9g",
    "carbs": "54g",
    "fat": "16g",
    "spice": "Medium",
    "isNew": true,
    "category": "veg"
  },
  {
    "id": "idlisambar",
    "name": "Steamed Idli Sambar (3 pcs)",
    "price": 140,
    "badge": "VEG",
    "region": "Tamil Nadu",
    "img": "images/idli-sambar.jpg",
    "emoji": "\u26aa",
    "desc": "Pillow-soft, fluffy fermented rice cakes steamed fresh to order, served immersed in aromatic piping hot drumstick sambar and fresh coconut chutney.",
    "ingredients": [
      "Parboiled rice",
      "Urad dal",
      "Fenugreek seeds",
      "Toor dal",
      "Drumsticks",
      "Shallots",
      "Tamarind",
      "Sambar powder",
      "Coconut chutney"
    ],
    "cal": 210,
    "protein": "9g",
    "carbs": "44g",
    "fat": "2g",
    "spice": "Mild",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "meduvada",
    "name": "Crispy Medu Vada (2 pcs)",
    "price": 150,
    "badge": "VEG",
    "region": "Tamil Nadu",
    "img": "images/medu-vada.jpg",
    "emoji": "\ud83c\udf69",
    "desc": "Traditional doughnut-shaped lentil fritters, intensely crispy on the outside and pillowy soft inside, spiced with black peppercorns, ginger, and curry leaves.",
    "ingredients": [
      "Urad dal",
      "Crushed black pepper",
      "Ginger",
      "Curry leaves",
      "Green chillies",
      "Asafoetida (Hing)",
      "Coconut bits",
      "Sambar"
    ],
    "cal": 290,
    "protein": "11g",
    "carbs": "32g",
    "fat": "14g",
    "spice": "Mild",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "gkeepongal",
    "name": "Ghee Ven Pongal",
    "price": 190,
    "badge": "VEG",
    "region": "Tamil Nadu",
    "img": "images/ven-pongal.jpg",
    "emoji": "\ud83c\udf5a",
    "desc": "Comforting South Indian dish made of rice and yellow moong dal cooked to creamy perfection, tempered generously in pure ghee with roasted cashews and black pepper.",
    "ingredients": [
      "Raw rice",
      "Yellow moong dal",
      "Desi ghee",
      "Whole cashews",
      "Black peppercorns",
      "Cumin seeds",
      "Ginger",
      "Curry leaves",
      "Sambar"
    ],
    "cal": 380,
    "protein": "10g",
    "carbs": "56g",
    "fat": "14g",
    "spice": "Mild",
    "isNew": true,
    "category": "veg"
  },
  {
    "id": "pbm",
    "name": "Paneer Butter Masala",
    "price": 320,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/paneer-butter-masala.jpg",
    "emoji": "\ud83c\udf72",
    "desc": "Velvety tomato-cashew gravy with soft paneer cubes, infused with aromatic kasuri methi and finished with fresh cream and butter.",
    "ingredients": [
      "Fresh paneer",
      "Vine-ripened tomatoes",
      "Amul butter",
      "Fresh cream",
      "Cashew paste",
      "Ginger-garlic",
      "Kasuri methi",
      "Garam masala"
    ],
    "cal": 420,
    "protein": "16g",
    "carbs": "18g",
    "fat": "32g",
    "spice": "Mild",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "dalm",
    "name": "Dal Makhani (Overnight Simmered)",
    "price": 280,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/dal-makhani.jpg",
    "emoji": "\ud83c\udf72",
    "desc": "Whole black lentils and kidney beans slow-cooked for 16 hours over charcoal tandoor with tomato puree, white butter, and fresh cream.",
    "ingredients": [
      "Urad sabut (Black lentils)",
      "Rajma (Kidney beans)",
      "White butter",
      "Fresh cream",
      "Tomato puree",
      "Ginger",
      "Garlic",
      "Degi mirch"
    ],
    "cal": 390,
    "protein": "14g",
    "carbs": "34g",
    "fat": "20g",
    "spice": "Mild",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "palak",
    "name": "Palak Paneer",
    "price": 300,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/palak-paneer.jpg",
    "emoji": "\ud83e\udd6c",
    "desc": "Fresh blanched spinach puree tempered with garlic, cumin, and mild spices, gently simmered with soft cottage cheese cubes.",
    "ingredients": [
      "Fresh spinach",
      "Paneer",
      "Garlic",
      "Cumin",
      "Green chillies",
      "Ginger",
      "Fresh cream",
      "Kasuri methi",
      "Garam masala"
    ],
    "cal": 360,
    "protein": "15g",
    "carbs": "14g",
    "fat": "26g",
    "spice": "Mild",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "kadaipaneer",
    "name": "Kadai Paneer",
    "price": 310,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/kadai-paneer.jpg",
    "emoji": "\ud83e\udd58",
    "desc": "Cottage cheese cubes and crunchy bell peppers tossed with freshly pounded coriander seeds and dry red chillies in an iron kadai gravy.",
    "ingredients": [
      "Paneer",
      "Bell peppers (Capsicum)",
      "Onion petals",
      "Tomatoes",
      "Whole coriander seeds",
      "Dry Kashmiri chillies",
      "Ginger",
      "Kasuri methi"
    ],
    "cal": 350,
    "protein": "14g",
    "carbs": "16g",
    "fat": "22g",
    "spice": "Medium",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "malaikofta",
    "name": "Shahi Malai Kofta",
    "price": 340,
    "badge": "VEG",
    "region": "Mughlai",
    "img": "images/malai-kofta.jpg",
    "emoji": "\ud83c\udf72",
    "desc": "Melt-in-mouth dumplings of paneer, khoya and dry fruits fried golden and served in a luxurious, creamy cashew-onion white gravy.",
    "ingredients": [
      "Paneer",
      "Khoya",
      "Cashews",
      "Raisins",
      "Cardamom",
      "Cashew nut paste",
      "Fresh cream",
      "Onion puree",
      "Saffron",
      "Rose water"
    ],
    "cal": 460,
    "protein": "13g",
    "carbs": "26g",
    "fat": "34g",
    "spice": "Mild",
    "isNew": true,
    "category": "veg"
  },
  {
    "id": "chana",
    "name": "Pindi Chana Masala",
    "price": 260,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/chana-masala.jpg",
    "emoji": "\ud83e\udd58",
    "desc": "Amritsari style dark chickpeas boiled with black tea leaves, tossed in aromatic dry spices, pomegranate seeds (anardana), and amchur.",
    "ingredients": [
      "Kabuli chickpeas",
      "Anardana (Pomegranate powder)",
      "Amchur",
      "Black tea infusion",
      "Ginger juliennes",
      "Slit green chillies",
      "Ghee",
      "Garam masala"
    ],
    "cal": 340,
    "protein": "14g",
    "carbs": "46g",
    "fat": "10g",
    "spice": "Medium",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "sarsonkasaag",
    "name": "Sarson Ka Saag (with Makki Roti)",
    "price": 310,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/sarson-saag.jpg",
    "emoji": "\ud83e\udd6c",
    "desc": "Authentic winter Punjabi mustard greens slow-cooked with bathua, spinach, and makki atta, tempered with ginger and desi ghee. Served with 2 Makki Roti and jaggery.",
    "ingredients": [
      "Mustard leaves (Sarson)",
      "Bathua",
      "Spinach",
      "Cornmeal (Makki atta)",
      "Ginger",
      "Garlic",
      "Green chillies",
      "Desi ghee",
      "Makki roti",
      "Gud (Jaggery)"
    ],
    "cal": 440,
    "protein": "12g",
    "carbs": "52g",
    "fat": "20g",
    "spice": "Medium",
    "isNew": true,
    "category": "veg"
  },
  {
    "id": "vbiriyani",
    "name": "Hyderabadi Veg Dum Biryani",
    "price": 340,
    "badge": "VEG",
    "region": "Hyderabad",
    "img": "images/veg-biryani.jpg",
    "emoji": "\ud83c\udf5a",
    "desc": "Fragrant basmati rice layered with seasonal vegetables, saffron, mint, and fried onions, slow-cooked in handi sealed with dough.",
    "ingredients": [
      "Basmati rice",
      "French beans",
      "Carrots",
      "Cauliflower",
      "Paneer",
      "Saffron",
      "Fried onions",
      "Mint",
      "Curd",
      "Ghee"
    ],
    "cal": 520,
    "protein": "10g",
    "carbs": "80g",
    "fat": "18g",
    "spice": "Medium",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "curdrice",
    "name": "Temple Style Curd Rice",
    "price": 160,
    "badge": "VEG",
    "region": "Tamil Nadu",
    "img": "images/curd-rice.jpg",
    "emoji": "\ud83c\udf5a",
    "desc": "Creamy soft cooked rice blended with fresh homemade curd and milk, tempered with mustard seeds, curry leaves, ginger, green chillies, and topped with pomegranate pearls.",
    "ingredients": [
      "Soft cooked rice",
      "Fresh thick curd",
      "Milk",
      "Mustard seeds",
      "Curry leaves",
      "Ginger",
      "Green chillies",
      "Hing",
      "Pomegranate seeds"
    ],
    "cal": 260,
    "protein": "8g",
    "carbs": "42g",
    "fat": "7g",
    "spice": "Mild",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "garlicnaan",
    "name": "Garlic Butter Naan",
    "price": 80,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/garlic-naan.jpg",
    "emoji": "\ud83e\uded3",
    "desc": "Soft leavened flatbread baked in clay tandoor, topped with minced garlic, fresh coriander, and brushed with melted butter.",
    "ingredients": [
      "Refined flour",
      "Milk",
      "Curd",
      "Fresh garlic",
      "Amul butter",
      "Coriander",
      "Yeast",
      "Nigella seeds (Kalonji)"
    ],
    "cal": 260,
    "protein": "7g",
    "carbs": "40g",
    "fat": "9g",
    "spice": "None",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "amritsarikulcha",
    "name": "Amritsari Aloo Kulcha",
    "price": 120,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/stuffed-kulcha.jpg",
    "emoji": "\ud83e\uded3",
    "desc": "Crispy layered tandoor-baked bread stuffed with spiced mashed potatoes, onions, anardana, and green chillies, topped with butter.",
    "ingredients": [
      "Maida",
      "Boiled potatoes",
      "Anardana (Pomegranate seeds)",
      "Chopped onions",
      "Ajwain",
      "Green chillies",
      "Amul butter"
    ],
    "cal": 290,
    "protein": "9g",
    "carbs": "42g",
    "fat": "10g",
    "spice": "Mild",
    "isNew": false,
    "category": "veg"
  },
  {
    "id": "bc",
    "name": "Old Delhi Butter Chicken",
    "price": 420,
    "badge": "NON-VEG",
    "region": "Delhi",
    "img": "images/butter-chicken.jpg",
    "emoji": "\ud83c\udf57",
    "desc": "Tandoor-charred chicken pieces simmered in silky smooth, mildly spiced tomato gravy with honey, butter, fenugreek, and cream.",
    "ingredients": [
      "Tandoori chicken",
      "Vine-ripened tomatoes",
      "Butter",
      "Fresh cream",
      "Kasuri methi",
      "Ginger-garlic",
      "Kashmiri chilli",
      "Cardamom",
      "Honey"
    ],
    "cal": 480,
    "protein": "36g",
    "carbs": "16g",
    "fat": "30g",
    "spice": "Mild",
    "isNew": false,
    "category": "nonveg"
  },
  {
    "id": "cbiriyani",
    "name": "Hyderabadi Chicken Dum Biryani",
    "price": 380,
    "badge": "NON-VEG",
    "region": "Hyderabad",
    "img": "images/chicken-biryani.jpg",
    "emoji": "\ud83c\udf57",
    "desc": "Authentic Kachchi Dum Biryani: tender bone-in chicken marinated overnight in spices and curd, slow-cooked in handi layered with fragrant saffron basmati rice.",
    "ingredients": [
      "Aged basmati rice",
      "Bone-in chicken",
      "Saffron",
      "Caramelised onions (Birista)",
      "Mint leaves",
      "Curd",
      "Shahi jeera",
      "Ghee",
      "Kewra water"
    ],
    "cal": 680,
    "protein": "38g",
    "carbs": "76g",
    "fat": "24g",
    "spice": "Medium",
    "isNew": false,
    "category": "nonveg"
  },
  {
    "id": "rogan",
    "name": "Mutton Rogan Josh",
    "price": 480,
    "badge": "NON-VEG",
    "region": "Kashmir",
    "img": "images/rogan-josh.jpg",
    "emoji": "\ud83e\udd69",
    "desc": "Succulent chunks of bone-in mutton slow-braised in an aromatic crimson gravy infused with Kashmiri red chillies, fennel powder, and mawal flowers.",
    "ingredients": [
      "Tender goat meat",
      "Mustard oil",
      "Kashmiri red chillies",
      "Fennel powder (Saunf)",
      "Dry ginger (Sonth)",
      "Black cardamom",
      "Cinnamon",
      "Whisked curd"
    ],
    "cal": 560,
    "protein": "42g",
    "carbs": "8g",
    "fat": "38g",
    "spice": "Hot",
    "isNew": false,
    "category": "nonveg"
  },
  {
    "id": "chettinadchicken",
    "name": "Chettinad Spicy Chicken Curry",
    "price": 410,
    "badge": "NON-VEG",
    "region": "Tamil Nadu",
    "img": "images/chettinad-chicken.jpg",
    "emoji": "\ud83c\udf57",
    "desc": "Fiery Tamil Nadu delicacy: chicken braised in freshly roasted black pepper, kalpasi (stone flower), star anise, fennel, and grated coconut paste.",
    "ingredients": [
      "Country chicken",
      "Black peppercorns",
      "Kalpasi (Stone flower)",
      "Star anise",
      "Fennel seeds",
      "Shallots",
      "Curry leaves",
      "Grated coconut",
      "Sesame oil"
    ],
    "cal": 450,
    "protein": "38g",
    "carbs": "10g",
    "fat": "28g",
    "spice": "Hot",
    "isNew": true,
    "category": "nonveg"
  },
  {
    "id": "fish",
    "name": "Kerala Malabar Fish Curry",
    "price": 420,
    "badge": "NON-VEG",
    "region": "Kerala",
    "img": "images/fish-curry.jpg",
    "emoji": "\ud83d\udc1f",
    "desc": "Fresh kingfish steaks cooked in earthen clay pots with thick coconut milk, tangy Kodampuli (Malabar kokum), shallots, and fragrant curry leaves.",
    "ingredients": [
      "Kingfish fillets",
      "Kodampuli (Malabar tamarind)",
      "Thick coconut milk",
      "Shallots",
      "Ginger & garlic",
      "Fenugreek seeds",
      "Curry leaves",
      "Coconut oil"
    ],
    "cal": 410,
    "protein": "38g",
    "carbs": "14g",
    "fat": "22g",
    "spice": "Hot",
    "isNew": false,
    "category": "nonveg"
  },
  {
    "id": "prawn",
    "name": "Goan Prawn Masala",
    "price": 520,
    "badge": "NON-VEG",
    "region": "Goa",
    "img": "images/prawn-masala.jpg",
    "emoji": "\ud83e\udd90",
    "desc": "Jumbo tiger prawns simmered in vibrant Goan peri-peri spiced red gravy with coconut vinegar, garlic, and freshly ground whole coastal spices.",
    "ingredients": [
      "Tiger prawns",
      "Kashmiri red chillies",
      "Toddy vinegar",
      "Garlic",
      "Cinnamon",
      "Cloves",
      "Cumin",
      "Onions",
      "Tomatoes",
      "Coconut oil"
    ],
    "cal": 390,
    "protein": "34g",
    "carbs": "10g",
    "fat": "24g",
    "spice": "Hot",
    "isNew": false,
    "category": "nonveg"
  },
  {
    "id": "andhrachicken",
    "name": "Andhra Kodi Vepudu (Spicy Chicken Fry)",
    "price": 390,
    "badge": "NON-VEG",
    "region": "Andhra Pradesh",
    "img": "images/andhra-chicken-fry.jpg",
    "emoji": "\ud83c\udf57",
    "desc": "Dry-roasted spicy Andhra chicken tossed on high flame with Guntur red chillies, crushed black pepper, fresh curry leaves, and caramelized shallots.",
    "ingredients": [
      "Chicken pieces",
      "Guntur dry red chillies",
      "Crushed black pepper",
      "Coriander seeds",
      "Curry leaves",
      "Shallots",
      "Ginger-garlic",
      "Lemon juice"
    ],
    "cal": 430,
    "protein": "40g",
    "carbs": "8g",
    "fat": "26g",
    "spice": "Hot",
    "isNew": true,
    "category": "nonveg"
  },
  {
    "id": "laalmaas",
    "name": "Rajasthani Royal Laal Maas",
    "price": 490,
    "badge": "NON-VEG",
    "region": "Rajasthan",
    "img": "images/laal-maas.jpg",
    "emoji": "\ud83e\udd69",
    "desc": "Heritage warrior dish of Rajasthan: tender goat meat cooked with pungent Mathania red chillies, garlic paste, and pure ghee with smoky charcoal aroma (dhungar).",
    "ingredients": [
      "Mutton chunks",
      "Mathania red chillies",
      "Garlic paste",
      "Desi ghee",
      "Curd",
      "Cloves",
      "Cardamom",
      "Kachri powder",
      "Charcoal smoke"
    ],
    "cal": 580,
    "protein": "44g",
    "carbs": "6g",
    "fat": "42g",
    "spice": "Hot",
    "isNew": true,
    "category": "nonveg"
  },
  {
    "id": "ctikkamasala",
    "name": "Chicken Tikka Masala",
    "price": 400,
    "badge": "NON-VEG",
    "region": "Punjab",
    "img": "images/chicken-tikka-masala.jpg",
    "emoji": "\ud83c\udf57",
    "desc": "Smoky char-grilled chicken tikka basted in spiced tandoori marinade, then tossed into a rich, robust onion-tomato masala gravy with capsicum.",
    "ingredients": [
      "Chicken tikka",
      "Onion-tomato gravy",
      "Capsicum",
      "Ginger",
      "Garlic",
      "Garam masala",
      "Kasuri methi",
      "Fresh cream",
      "Coriander"
    ],
    "cal": 460,
    "protein": "34g",
    "carbs": "18g",
    "fat": "28g",
    "spice": "Medium",
    "isNew": false,
    "category": "nonveg"
  },
  {
    "id": "lambbiriyani",
    "name": "Lucknowi Lamb Dum Biryani",
    "price": 460,
    "badge": "NON-VEG",
    "region": "Awadh",
    "img": "images/lamb-biryani.jpg",
    "emoji": "\ud83e\udd69",
    "desc": "Royal Awadhi Pakki Biryani: succulent tender lamb cooked in aromatic yakhni stock, layered with perfumed basmati rice, saffron milk, and ittar.",
    "ingredients": [
      "Lamb meat",
      "Aged basmati rice",
      "Lamb bone broth (Yakhni)",
      "Saffron",
      "Rose water & ittar",
      "Desi ghee",
      "Cardamom & mace",
      "Fried onions"
    ],
    "cal": 720,
    "protein": "44g",
    "carbs": "72g",
    "fat": "28g",
    "spice": "Medium",
    "isNew": false,
    "category": "nonveg"
  },
  {
    "id": "ctikka",
    "name": "Chicken Malai Tikka",
    "price": 380,
    "badge": "NON-VEG",
    "region": "Mughlai",
    "img": "images/chicken-tikka.jpg",
    "emoji": "\ud83c\udf57",
    "desc": "Tender chicken chunks marinated in heavy cream, hung curd, cashew paste and mild white pepper, grilled on skewers in tandoor.",
    "ingredients": [
      "Boneless chicken",
      "Fresh cream",
      "Cashew paste",
      "Hung curd",
      "Ginger-garlic",
      "Cardamom powder",
      "White pepper",
      "Butter"
    ],
    "cal": 420,
    "protein": "34g",
    "carbs": "6g",
    "fat": "29g",
    "spice": "Mild",
    "isNew": false,
    "category": "nonveg"
  },
  {
    "id": "fishamritsari",
    "name": "Fish Amritsari Fry",
    "price": 360,
    "badge": "NON-VEG",
    "region": "Punjab",
    "img": "images/fish-amritsari.jpg",
    "emoji": "\ud83d\udc1f",
    "desc": "Fresh boneless fish fillets marinated in carom seeds (ajwain), ginger-garlic, and lemon juice, dipped in gram flour batter and fried crispy golden.",
    "ingredients": [
      "Fish fillets",
      "Besan (Gram flour)",
      "Ajwain",
      "Ginger-garlic paste",
      "Kashmiri red chilli",
      "Lemon juice",
      "Chaat masala",
      "Mustard oil"
    ],
    "cal": 390,
    "protein": "28g",
    "carbs": "18g",
    "fat": "22g",
    "spice": "Hot",
    "isNew": false,
    "category": "nonveg"
  },
  {
    "id": "samosa",
    "name": "Samosa Chaat",
    "price": 180,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/samosa.jpg",
    "emoji": "\ud83e\udd5f",
    "desc": "Crispy golden samosas crushed and topped with spiced chole, sweet tamarind, tangy mint chutneys, chilled curd and crunchy sev.",
    "ingredients": [
      "Wheat flour",
      "Potato",
      "Green peas",
      "Kabuli chana",
      "Tamarind chutney",
      "Mint chutney",
      "Curd",
      "Sev",
      "Chaat masala",
      "Pomegranate"
    ],
    "cal": 310,
    "protein": "8g",
    "carbs": "42g",
    "fat": "11g",
    "spice": "Medium",
    "isNew": false,
    "category": "snacks"
  },
  {
    "id": "panipuri",
    "name": "Pani Puri / Golgappe (8 pcs)",
    "price": 140,
    "badge": "VEG",
    "region": "Delhi",
    "img": "images/pani-puri.jpg",
    "emoji": "\ud83e\udd5f",
    "desc": "Crispy hollow semolina puris filled with spiced potato-chickpea mix, tangy hing-jeera water, and sweet dates-tamarind chutney.",
    "ingredients": [
      "Semolina puris",
      "Boiled potatoes",
      "Black chickpeas",
      "Mint & coriander water",
      "Tamarind chutney",
      "Black salt",
      "Hing",
      "Roasted cumin"
    ],
    "cal": 180,
    "protein": "4g",
    "carbs": "36g",
    "fat": "3g",
    "spice": "Hot",
    "isNew": true,
    "category": "snacks"
  },
  {
    "id": "pavbhaji",
    "name": "Amul Butter Pav Bhaji",
    "price": 220,
    "badge": "VEG",
    "region": "Mumbai",
    "img": "images/pav-bhaji.jpg",
    "emoji": "\ud83c\udf5b",
    "desc": "Spiced mashed vegetable curry slow-simmered on a giant tawa with secret Mumbai spices, topped with generous Amul butter, served with soft toasted pav.",
    "ingredients": [
      "Potatoes",
      "Cauliflower",
      "Green peas",
      "Tomatoes",
      "Capsicum",
      "Amul butter",
      "Pav bhaji masala",
      "Kasuri methi",
      "Pav bread",
      "Lemon & onion"
    ],
    "cal": 450,
    "protein": "11g",
    "carbs": "58g",
    "fat": "20g",
    "spice": "Medium",
    "isNew": true,
    "category": "snacks"
  },
  {
    "id": "vadapav",
    "name": "Mumbai Vada Pav (2 pcs)",
    "price": 120,
    "badge": "VEG",
    "region": "Mumbai",
    "img": "images/vada-pav.jpg",
    "emoji": "\ud83c\udf54",
    "desc": "Iconic spiced potato fritter coated in golden gram flour, tucked inside soft pav with spicy garlic dry chutney, fried green chillies, and sweet tamarind sauce.",
    "ingredients": [
      "Potatoes",
      "Gram flour (Besan)",
      "Mustard seeds",
      "Curry leaves",
      "Garlic dry chutney",
      "Green chillies",
      "Pav bread",
      "Turmeric"
    ],
    "cal": 320,
    "protein": "7g",
    "carbs": "44g",
    "fat": "13g",
    "spice": "Hot",
    "isNew": true,
    "category": "snacks"
  },
  {
    "id": "dahipuri",
    "name": "Dahi Puri Supreme",
    "price": 160,
    "badge": "VEG",
    "region": "Mumbai",
    "img": "images/dahi-puri.jpg",
    "emoji": "\ud83e\udd63",
    "desc": "Crispy puris stuffed with boiled potato cubes and moong sprouts, drenched in sweet whipped yoghurt, tamarind glaze, green chutney, and fine nylon sev.",
    "ingredients": [
      "Puri",
      "Boiled potato",
      "Sprouted moong",
      "Sweet curd",
      "Tamarind chutney",
      "Mint chutney",
      "Nylon sev",
      "Pomegranate",
      "Chaat masala"
    ],
    "cal": 240,
    "protein": "6g",
    "carbs": "36g",
    "fat": "8g",
    "spice": "Mild",
    "isNew": false,
    "category": "snacks"
  },
  {
    "id": "bhelpuri",
    "name": "Chowpatty Bhel Puri",
    "price": 130,
    "badge": "VEG",
    "region": "Mumbai",
    "img": "images/bhel-puri.jpg",
    "emoji": "\ud83e\udd57",
    "desc": "Light puffed rice tossed with roasted peanuts, crushed papdi, diced onions, tomatoes, raw mango, fresh coriander, and sweet-spicy chutneys.",
    "ingredients": [
      "Puffed rice (Kurmura)",
      "Nylon sev",
      "Papdi",
      "Roasted peanuts",
      "Onion",
      "Tomato",
      "Raw mango",
      "Tamarind chutney",
      "Chilli chutney",
      "Lemon"
    ],
    "cal": 190,
    "protein": "5g",
    "carbs": "35g",
    "fat": "4g",
    "spice": "Medium",
    "isNew": true,
    "category": "snacks"
  },
  {
    "id": "onionpakoda",
    "name": "Crispy Kanda / Onion Pakoda",
    "price": 150,
    "badge": "VEG",
    "region": "Maharashtra",
    "img": "images/onion-pakoda.jpg",
    "emoji": "\ud83e\uddc5",
    "desc": "Thinly sliced red onions tossed with ajwain, green chillies, fresh coriander and besan, deep-fried extra crunchy. Perfect snack with mint chutney.",
    "ingredients": [
      "Red onions",
      "Besan (Gram flour)",
      "Rice flour",
      "Ajwain (Carom seeds)",
      "Green chillies",
      "Coriander",
      "Red chilli powder",
      "Hing",
      "Oil"
    ],
    "cal": 280,
    "protein": "6g",
    "carbs": "30g",
    "fat": "15g",
    "spice": "Medium",
    "isNew": true,
    "category": "snacks"
  },
  {
    "id": "mirchibajji",
    "name": "Andhra Mirchi Bajji (4 pcs)",
    "price": 160,
    "badge": "VEG",
    "region": "Andhra Pradesh",
    "img": "images/mirchi-bajji.jpg",
    "emoji": "\ud83c\udf36\ufe0f",
    "desc": "Large Bhavnagri green chillies stuffed with tangy ajwain-tamarind paste, dipped in spiced chickpea batter, fried golden and cut open with chopped onion and chaat masala.",
    "ingredients": [
      "Large green chillies",
      "Besan",
      "Tamarind pulp",
      "Ajwain",
      "Cumin",
      "Chopped onions",
      "Lemon juice",
      "Chaat masala",
      "Oil"
    ],
    "cal": 260,
    "protein": "7g",
    "carbs": "28g",
    "fat": "14g",
    "spice": "Hot",
    "isNew": true,
    "category": "snacks"
  },
  {
    "id": "paneerpakoda",
    "name": "Amritsari Paneer Pakoda",
    "price": 240,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/paneer-pakoda.jpg",
    "emoji": "\ud83e\uddc0",
    "desc": "Thick slices of malai paneer sandwiched with tangy mint-chutney, dipped in spiced ajwain-besan batter, and fried golden. Melting interior.",
    "ingredients": [
      "Malai paneer",
      "Besan",
      "Ajwain",
      "Mint chutney",
      "Kasuri methi",
      "Chaat masala",
      "Red chilli",
      "Ginger-garlic paste",
      "Oil"
    ],
    "cal": 380,
    "protein": "18g",
    "carbs": "16g",
    "fat": "27g",
    "spice": "Mild",
    "isNew": true,
    "category": "snacks"
  },
  {
    "id": "harabharakabab",
    "name": "Hara Bhara Kabab",
    "price": 260,
    "badge": "VEG",
    "region": "Delhi",
    "img": "images/hara-bhara-kabab.jpg",
    "emoji": "\ud83e\udd6c",
    "desc": "Vibrant emerald patties made with spinach, green peas, mashed potatoes and cottage cheese, scented with cardamom and topped with cashew nut.",
    "ingredients": [
      "Fresh spinach",
      "Green peas",
      "Paneer",
      "Potato",
      "Ginger",
      "Green chilli",
      "Cashew nut",
      "Cardamom",
      "Chaat masala",
      "Cornflour"
    ],
    "cal": 230,
    "protein": "10g",
    "carbs": "24g",
    "fat": "10g",
    "spice": "Mild",
    "isNew": false,
    "category": "snacks"
  },
  {
    "id": "alootikki",
    "name": "Crispy Aloo Tikki Chaat",
    "price": 160,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/aloo-tikki.jpg",
    "emoji": "\ud83e\udd54",
    "desc": "Golden fried spiced potato patties topped with warm kabuli chana, sweet tamarind chutney, green mint sauce, whisked curd, and fresh ginger juliennes.",
    "ingredients": [
      "Boiled potatoes",
      "Green peas",
      "Cornflour",
      "Cumin",
      "Ginger",
      "Chana masala",
      "Curd",
      "Tamarind chutney",
      "Mint chutney",
      "Chaat masala"
    ],
    "cal": 290,
    "protein": "6g",
    "carbs": "44g",
    "fat": "10g",
    "spice": "Medium",
    "isNew": false,
    "category": "snacks"
  },
  {
    "id": "lassi",
    "name": "Royal Mango Lassi",
    "price": 120,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/mango-lassi.jpg",
    "emoji": "\ud83e\udd6d",
    "desc": "Thick chilled sweet yoghurt blended with real Ratnagiri Alphonso mango pulp, green cardamom, and garnished with saffron strands and pistachios.",
    "ingredients": [
      "Alphonso mango pulp",
      "Thick sweet curd",
      "Fresh cream",
      "Cardamom powder",
      "Saffron",
      "Pistachios"
    ],
    "cal": 240,
    "protein": "6g",
    "carbs": "38g",
    "fat": "8g",
    "spice": "None",
    "isNew": false,
    "category": "drinks"
  },
  {
    "id": "filtercoffee",
    "name": "Madras Degree Filter Coffee",
    "price": 80,
    "badge": "VEG",
    "region": "Tamil Nadu",
    "img": "images/filter-coffee.jpg",
    "emoji": "\u2615",
    "desc": "Authentic South Indian decoction brewed with fresh dark roast chicory coffee beans and foamy boiled full-fat milk in traditional brass davarah and tumbler.",
    "ingredients": [
      "80:20 Plantation coffee & chicory blend",
      "Full-fat milk",
      "Sugar"
    ],
    "cal": 110,
    "protein": "4g",
    "carbs": "16g",
    "fat": "4g",
    "spice": "None",
    "isNew": true,
    "category": "drinks"
  },
  {
    "id": "chai",
    "name": "Kadak Masala Chai",
    "price": 60,
    "badge": "VEG",
    "region": "North India",
    "img": "images/masala-chai.jpg",
    "emoji": "\u2615",
    "desc": "Strong Assam tea brewed with crushed ginger, green cardamom, cinnamon, cloves, black pepper, and fresh whole milk. Served piping hot.",
    "ingredients": [
      "Assam CTC tea",
      "Fresh milk",
      "Crushed ginger",
      "Green cardamom",
      "Cinnamon",
      "Cloves",
      "Black pepper",
      "Sugar"
    ],
    "cal": 80,
    "protein": "3g",
    "carbs": "14g",
    "fat": "3g",
    "spice": "None",
    "isNew": false,
    "category": "drinks"
  },
  {
    "id": "sweetlassi",
    "name": "Punjabi Malai Sweet Lassi",
    "price": 110,
    "badge": "VEG",
    "region": "Punjab",
    "img": "images/sweet-lassi.jpg",
    "emoji": "\ud83e\udd5b",
    "desc": "Hand-churned creamy thick yoghurt drink flavored with fragrant rose water and cardamom, topped with thick clotted malai and crushed almonds.",
    "ingredients": [
      "Fresh thick curd",
      "Sugar",
      "Rose water",
      "Cardamom",
      "Fresh malai (Cream)",
      "Almonds",
      "Pistachios"
    ],
    "cal": 260,
    "protein": "7g",
    "carbs": "36g",
    "fat": "10g",
    "spice": "None",
    "isNew": true,
    "category": "drinks"
  },
  {
    "id": "rose_sharbat",
    "name": "Old Delhi Rose Sharbat with Sabja",
    "price": 90,
    "badge": "VEG",
    "region": "Lucknow",
    "img": "images/rose-sharbat.jpg",
    "emoji": "\ud83c\udf39",
    "desc": "Chilled traditional Rooh Afza rose cordial infused with soaked basil seeds (sabja), a squeeze of fresh lime, and crushed mint leaves.",
    "ingredients": [
      "Rooh Afza rose syrup",
      "Soaked sabja (Basil seeds)",
      "Fresh lime juice",
      "Chilled water",
      "Mint sprigs",
      "Ice"
    ],
    "cal": 120,
    "protein": "0g",
    "carbs": "30g",
    "fat": "0g",
    "spice": "None",
    "isNew": false,
    "category": "drinks"
  },
  {
    "id": "masala_chaas",
    "name": "Masala Buttermilk (Chaas)",
    "price": 70,
    "badge": "VEG",
    "region": "Gujarat",
    "img": "images/masala-chaas.jpg",
    "emoji": "\ud83e\udd5b",
    "desc": "Refreshing chilled buttermilk churned with roasted cumin powder, black salt, grated ginger, green chillies, fresh coriander, and curry leaves.",
    "ingredients": [
      "Fresh churned curd",
      "Roasted cumin (Bhuna jeera)",
      "Kala namak (Black salt)",
      "Ginger",
      "Green chilli",
      "Coriander",
      "Curry leaves"
    ],
    "cal": 65,
    "protein": "3g",
    "carbs": "6g",
    "fat": "3g",
    "spice": "Mild",
    "isNew": true,
    "category": "drinks"
  },
  {
    "id": "gulab",
    "name": "Royal Shahi Gulab Jamun (2 pcs)",
    "price": 120,
    "badge": "VEG",
    "region": "North India",
    "img": "images/gulab-jamun.jpg",
    "emoji": "\ud83c\udf6f",
    "desc": "Golden fried khoya dumplings infused with saffron and pistachios, soaked warm in rosewater-cardamom sugar syrup.",
    "ingredients": [
      "Fresh khoya (Mawa)",
      "Chhena",
      "Cardamom",
      "Rose water",
      "Saffron (Kesar)",
      "Pistachios",
      "Sugar syrup",
      "Desi ghee"
    ],
    "cal": 320,
    "protein": "6g",
    "carbs": "46g",
    "fat": "13g",
    "spice": "None",
    "isNew": false,
    "category": "drinks"
  },
  {
    "id": "rasmalai",
    "name": "Kesar Pista Rasmalai (2 pcs)",
    "price": 160,
    "badge": "VEG",
    "region": "Bengal",
    "img": "images/rasmalai.jpg",
    "emoji": "\ud83e\udd5b",
    "desc": "Spongy cottage cheese patties poached in sugar syrup and steeped in chilled, thickened saffron milk topped with sliced pistachios and almonds.",
    "ingredients": [
      "Chhena (Cottage cheese)",
      "Full-cream milk",
      "Kashmiri saffron",
      "Cardamom",
      "Pistachios",
      "Almonds",
      "Sugar"
    ],
    "cal": 280,
    "protein": "10g",
    "carbs": "38g",
    "fat": "10g",
    "spice": "None",
    "isNew": false,
    "category": "drinks"
  },
  {
    "id": "kulfi",
    "name": "Old Delhi Kulfi Falooda",
    "price": 180,
    "badge": "VEG",
    "region": "Old Delhi",
    "img": "images/kulfi-falooda.jpg",
    "emoji": "\ud83c\udf68",
    "desc": "Dense, traditional malai kulfi sliced and served over chilled cornstarch falooda vermicelli, rose syrup, and blooming sabja seeds.",
    "ingredients": [
      "Traditional malai kulfi",
      "Falooda sev",
      "Rooh Afza rose syrup",
      "Sabja (Basil seeds)",
      "Pistachios",
      "Rabri"
    ],
    "cal": 350,
    "protein": "8g",
    "carbs": "44g",
    "fat": "16g",
    "spice": "None",
    "isNew": false,
    "category": "drinks"
  }
];
